// <auto-generated by MavNet.CodeGen />
using System.Buffers.Binary;
using MavNet.Protocol;
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Messages;

public readonly record struct CommandLong(
    float Param1,
    float Param2,
    float Param3,
    float Param4,
    float Param5,
    float Param6,
    float Param7,
    MavCmd Command,
    byte TargetSystem,
    byte TargetComponent,
    byte Confirmation) : IMavlinkMessage<CommandLong>
{
    public const uint MsgId = 76u;
    public const byte CrcExtra = 152;
    public const byte MinPayloadLength = 33;
    public const byte MaxPayloadLength = 33;

    static uint IMavlinkMessage<CommandLong>.MsgId             => MsgId;
    static byte IMavlinkMessage<CommandLong>.CrcExtra          => CrcExtra;
    static byte IMavlinkMessage<CommandLong>.MinPayloadLength  => MinPayloadLength;
    static byte IMavlinkMessage<CommandLong>.MaxPayloadLength  => MaxPayloadLength;

    public static CommandLong Decode(System.ReadOnlySpan<byte> payload)
    {
        // MAVLink v2 senders may strip trailing zero bytes — pad up to max length.
        System.Span<byte> p = stackalloc byte[MaxPayloadLength];
        payload[..System.Math.Min(payload.Length, (int)MaxPayloadLength)].CopyTo(p);
        return new CommandLong(
            BinaryPrimitives.ReadSingleLittleEndian(p[0..4]),
            BinaryPrimitives.ReadSingleLittleEndian(p[4..8]),
            BinaryPrimitives.ReadSingleLittleEndian(p[8..12]),
            BinaryPrimitives.ReadSingleLittleEndian(p[12..16]),
            BinaryPrimitives.ReadSingleLittleEndian(p[16..20]),
            BinaryPrimitives.ReadSingleLittleEndian(p[20..24]),
            BinaryPrimitives.ReadSingleLittleEndian(p[24..28]),
            (MavCmd)BinaryPrimitives.ReadUInt16LittleEndian(p[28..30]),
            p[30],
            p[31],
            p[32]);
    }

    /// <summary>Encode the full untruncated payload. Caller may strip trailing zero bytes
    /// down to <see cref="MinPayloadLength"/> for on-wire MAVLink v2 truncation.</summary>
    public void Encode(System.Span<byte> payload)
    {
        BinaryPrimitives.WriteSingleLittleEndian(payload[0..4], Param1);
        BinaryPrimitives.WriteSingleLittleEndian(payload[4..8], Param2);
        BinaryPrimitives.WriteSingleLittleEndian(payload[8..12], Param3);
        BinaryPrimitives.WriteSingleLittleEndian(payload[12..16], Param4);
        BinaryPrimitives.WriteSingleLittleEndian(payload[16..20], Param5);
        BinaryPrimitives.WriteSingleLittleEndian(payload[20..24], Param6);
        BinaryPrimitives.WriteSingleLittleEndian(payload[24..28], Param7);
        BinaryPrimitives.WriteUInt16LittleEndian(payload[28..30], (ushort)Command);
        payload[30] = TargetSystem;
        payload[31] = TargetComponent;
        payload[32] = Confirmation;
    }
}
