// <auto-generated by MavNet.CodeGen />
using System.Buffers.Binary;
using MavNet.Protocol;
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Messages;

public readonly record struct ExtendedSysState(
    MavVtolState VtolState,
    MavLandedState LandedState) : IMavlinkMessage<ExtendedSysState>
{
    public const uint MsgId = 245u;
    public const byte CrcExtra = 130;
    public const byte MinPayloadLength = 2;
    public const byte MaxPayloadLength = 2;

    static uint IMavlinkMessage<ExtendedSysState>.MsgId             => MsgId;
    static byte IMavlinkMessage<ExtendedSysState>.CrcExtra          => CrcExtra;
    static byte IMavlinkMessage<ExtendedSysState>.MinPayloadLength  => MinPayloadLength;
    static byte IMavlinkMessage<ExtendedSysState>.MaxPayloadLength  => MaxPayloadLength;

    public static ExtendedSysState Decode(System.ReadOnlySpan<byte> payload)
    {
        // MAVLink v2 senders may strip trailing zero bytes — pad up to max length.
        System.Span<byte> p = stackalloc byte[MaxPayloadLength];
        payload[..System.Math.Min(payload.Length, (int)MaxPayloadLength)].CopyTo(p);
        return new ExtendedSysState(
            (MavVtolState)p[0],
            (MavLandedState)p[1]);
    }

    /// <summary>Encode the full untruncated payload. Caller may strip trailing zero bytes
    /// down to <see cref="MinPayloadLength"/> for on-wire MAVLink v2 truncation.</summary>
    public void Encode(System.Span<byte> payload)
    {
        payload[0] = (byte)VtolState;
        payload[1] = (byte)LandedState;
    }
}
