// <auto-generated by MavNet.CodeGen />
using System.Buffers.Binary;
using MavNet.Protocol;
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Messages;

public readonly record struct GlobalPositionInt(
    uint TimeBootMs,
    int Lat,
    int Lon,
    int Alt,
    int RelativeAlt,
    short Vx,
    short Vy,
    short Vz,
    ushort Hdg) : IMavlinkMessage<GlobalPositionInt>
{
    public const uint MsgId = 33u;
    public const byte CrcExtra = 104;
    public const byte MinPayloadLength = 28;
    public const byte MaxPayloadLength = 28;

    static uint IMavlinkMessage<GlobalPositionInt>.MsgId             => MsgId;
    static byte IMavlinkMessage<GlobalPositionInt>.CrcExtra          => CrcExtra;
    static byte IMavlinkMessage<GlobalPositionInt>.MinPayloadLength  => MinPayloadLength;
    static byte IMavlinkMessage<GlobalPositionInt>.MaxPayloadLength  => MaxPayloadLength;

    public static GlobalPositionInt Decode(System.ReadOnlySpan<byte> payload)
    {
        // MAVLink v2 senders may strip trailing zero bytes — pad up to max length.
        System.Span<byte> p = stackalloc byte[MaxPayloadLength];
        payload[..System.Math.Min(payload.Length, (int)MaxPayloadLength)].CopyTo(p);
        return new GlobalPositionInt(
            BinaryPrimitives.ReadUInt32LittleEndian(p[0..4]),
            BinaryPrimitives.ReadInt32LittleEndian(p[4..8]),
            BinaryPrimitives.ReadInt32LittleEndian(p[8..12]),
            BinaryPrimitives.ReadInt32LittleEndian(p[12..16]),
            BinaryPrimitives.ReadInt32LittleEndian(p[16..20]),
            BinaryPrimitives.ReadInt16LittleEndian(p[20..22]),
            BinaryPrimitives.ReadInt16LittleEndian(p[22..24]),
            BinaryPrimitives.ReadInt16LittleEndian(p[24..26]),
            BinaryPrimitives.ReadUInt16LittleEndian(p[26..28]));
    }

    /// <summary>Encode the full untruncated payload. Caller may strip trailing zero bytes
    /// down to <see cref="MinPayloadLength"/> for on-wire MAVLink v2 truncation.</summary>
    public void Encode(System.Span<byte> payload)
    {
        BinaryPrimitives.WriteUInt32LittleEndian(payload[0..4], TimeBootMs);
        BinaryPrimitives.WriteInt32LittleEndian(payload[4..8], Lat);
        BinaryPrimitives.WriteInt32LittleEndian(payload[8..12], Lon);
        BinaryPrimitives.WriteInt32LittleEndian(payload[12..16], Alt);
        BinaryPrimitives.WriteInt32LittleEndian(payload[16..20], RelativeAlt);
        BinaryPrimitives.WriteInt16LittleEndian(payload[20..22], Vx);
        BinaryPrimitives.WriteInt16LittleEndian(payload[22..24], Vy);
        BinaryPrimitives.WriteInt16LittleEndian(payload[24..26], Vz);
        BinaryPrimitives.WriteUInt16LittleEndian(payload[26..28], Hdg);
    }
}
