// <auto-generated by MavNet.CodeGen />
using System.Buffers.Binary;
using MavNet.Protocol;
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Messages;

public readonly record struct GpsRawInt(
    ulong TimeUsec,
    int Lat,
    int Lon,
    int Alt,
    ushort Eph,
    ushort Epv,
    ushort Vel,
    ushort Cog,
    GpsFixType FixType,
    byte SatellitesVisible,
    int AltEllipsoid,
    uint HAcc,
    uint VAcc,
    uint VelAcc,
    uint HdgAcc,
    ushort Yaw) : IMavlinkMessage<GpsRawInt>
{
    public const uint MsgId = 24u;
    public const byte CrcExtra = 24;
    public const byte MinPayloadLength = 30;
    public const byte MaxPayloadLength = 52;

    static uint IMavlinkMessage<GpsRawInt>.MsgId             => MsgId;
    static byte IMavlinkMessage<GpsRawInt>.CrcExtra          => CrcExtra;
    static byte IMavlinkMessage<GpsRawInt>.MinPayloadLength  => MinPayloadLength;
    static byte IMavlinkMessage<GpsRawInt>.MaxPayloadLength  => MaxPayloadLength;

    public static GpsRawInt Decode(System.ReadOnlySpan<byte> payload)
    {
        // MAVLink v2 senders may strip trailing zero bytes — pad up to max length.
        System.Span<byte> p = stackalloc byte[MaxPayloadLength];
        payload[..System.Math.Min(payload.Length, (int)MaxPayloadLength)].CopyTo(p);
        return new GpsRawInt(
            BinaryPrimitives.ReadUInt64LittleEndian(p[0..8]),
            BinaryPrimitives.ReadInt32LittleEndian(p[8..12]),
            BinaryPrimitives.ReadInt32LittleEndian(p[12..16]),
            BinaryPrimitives.ReadInt32LittleEndian(p[16..20]),
            BinaryPrimitives.ReadUInt16LittleEndian(p[20..22]),
            BinaryPrimitives.ReadUInt16LittleEndian(p[22..24]),
            BinaryPrimitives.ReadUInt16LittleEndian(p[24..26]),
            BinaryPrimitives.ReadUInt16LittleEndian(p[26..28]),
            (GpsFixType)p[28],
            p[29],
            BinaryPrimitives.ReadInt32LittleEndian(p[30..34]),
            BinaryPrimitives.ReadUInt32LittleEndian(p[34..38]),
            BinaryPrimitives.ReadUInt32LittleEndian(p[38..42]),
            BinaryPrimitives.ReadUInt32LittleEndian(p[42..46]),
            BinaryPrimitives.ReadUInt32LittleEndian(p[46..50]),
            BinaryPrimitives.ReadUInt16LittleEndian(p[50..52]));
    }

    /// <summary>Encode the full untruncated payload. Caller may strip trailing zero bytes
    /// down to <see cref="MinPayloadLength"/> for on-wire MAVLink v2 truncation.</summary>
    public void Encode(System.Span<byte> payload)
    {
        BinaryPrimitives.WriteUInt64LittleEndian(payload[0..8], TimeUsec);
        BinaryPrimitives.WriteInt32LittleEndian(payload[8..12], Lat);
        BinaryPrimitives.WriteInt32LittleEndian(payload[12..16], Lon);
        BinaryPrimitives.WriteInt32LittleEndian(payload[16..20], Alt);
        BinaryPrimitives.WriteUInt16LittleEndian(payload[20..22], Eph);
        BinaryPrimitives.WriteUInt16LittleEndian(payload[22..24], Epv);
        BinaryPrimitives.WriteUInt16LittleEndian(payload[24..26], Vel);
        BinaryPrimitives.WriteUInt16LittleEndian(payload[26..28], Cog);
        payload[28] = (byte)FixType;
        payload[29] = SatellitesVisible;
        BinaryPrimitives.WriteInt32LittleEndian(payload[30..34], AltEllipsoid);
        BinaryPrimitives.WriteUInt32LittleEndian(payload[34..38], HAcc);
        BinaryPrimitives.WriteUInt32LittleEndian(payload[38..42], VAcc);
        BinaryPrimitives.WriteUInt32LittleEndian(payload[42..46], VelAcc);
        BinaryPrimitives.WriteUInt32LittleEndian(payload[46..50], HdgAcc);
        BinaryPrimitives.WriteUInt16LittleEndian(payload[50..52], Yaw);
    }
}
