// <auto-generated by MavNet.CodeGen />
using System.Buffers.Binary;
using MavNet.Protocol;
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Messages;

public readonly record struct Heartbeat(
    uint CustomMode,
    MavType Type,
    MavAutopilot Autopilot,
    MavModeFlag BaseMode,
    MavState SystemStatus,
    byte MavlinkVersion) : IMavlinkMessage<Heartbeat>
{
    public const uint MsgId = 0u;
    public const byte CrcExtra = 50;
    public const byte MinPayloadLength = 9;
    public const byte MaxPayloadLength = 9;

    static uint IMavlinkMessage<Heartbeat>.MsgId             => MsgId;
    static byte IMavlinkMessage<Heartbeat>.CrcExtra          => CrcExtra;
    static byte IMavlinkMessage<Heartbeat>.MinPayloadLength  => MinPayloadLength;
    static byte IMavlinkMessage<Heartbeat>.MaxPayloadLength  => MaxPayloadLength;

    public static Heartbeat Decode(System.ReadOnlySpan<byte> payload)
    {
        // MAVLink v2 senders may strip trailing zero bytes — pad up to max length.
        System.Span<byte> p = stackalloc byte[MaxPayloadLength];
        payload[..System.Math.Min(payload.Length, (int)MaxPayloadLength)].CopyTo(p);
        return new Heartbeat(
            BinaryPrimitives.ReadUInt32LittleEndian(p[0..4]),
            (MavType)p[4],
            (MavAutopilot)p[5],
            (MavModeFlag)p[6],
            (MavState)p[7],
            p[8]);
    }

    /// <summary>Encode the full untruncated payload. Caller may strip trailing zero bytes
    /// down to <see cref="MinPayloadLength"/> for on-wire MAVLink v2 truncation.</summary>
    public void Encode(System.Span<byte> payload)
    {
        BinaryPrimitives.WriteUInt32LittleEndian(payload[0..4], CustomMode);
        payload[4] = (byte)Type;
        payload[5] = (byte)Autopilot;
        payload[6] = (byte)BaseMode;
        payload[7] = (byte)SystemStatus;
        payload[8] = MavlinkVersion;
    }
}
