// <auto-generated by MavNet.CodeGen />
using System.Buffers.Binary;
using MavNet.Protocol;
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Messages;

public readonly record struct MissionCurrent(
    ushort Seq,
    ushort Total,
    MissionState MissionState,
    byte MissionMode,
    uint MissionId,
    uint FenceId,
    uint RallyPointsId) : IMavlinkMessage<MissionCurrent>
{
    public const uint MsgId = 42u;
    public const byte CrcExtra = 28;
    public const byte MinPayloadLength = 2;
    public const byte MaxPayloadLength = 18;

    static uint IMavlinkMessage<MissionCurrent>.MsgId             => MsgId;
    static byte IMavlinkMessage<MissionCurrent>.CrcExtra          => CrcExtra;
    static byte IMavlinkMessage<MissionCurrent>.MinPayloadLength  => MinPayloadLength;
    static byte IMavlinkMessage<MissionCurrent>.MaxPayloadLength  => MaxPayloadLength;

    public static MissionCurrent Decode(System.ReadOnlySpan<byte> payload)
    {
        // MAVLink v2 senders may strip trailing zero bytes — pad up to max length.
        System.Span<byte> p = stackalloc byte[MaxPayloadLength];
        payload[..System.Math.Min(payload.Length, (int)MaxPayloadLength)].CopyTo(p);
        return new MissionCurrent(
            BinaryPrimitives.ReadUInt16LittleEndian(p[0..2]),
            BinaryPrimitives.ReadUInt16LittleEndian(p[2..4]),
            (MissionState)p[4],
            p[5],
            BinaryPrimitives.ReadUInt32LittleEndian(p[6..10]),
            BinaryPrimitives.ReadUInt32LittleEndian(p[10..14]),
            BinaryPrimitives.ReadUInt32LittleEndian(p[14..18]));
    }

    /// <summary>Encode the full untruncated payload. Caller may strip trailing zero bytes
    /// down to <see cref="MinPayloadLength"/> for on-wire MAVLink v2 truncation.</summary>
    public void Encode(System.Span<byte> payload)
    {
        BinaryPrimitives.WriteUInt16LittleEndian(payload[0..2], Seq);
        BinaryPrimitives.WriteUInt16LittleEndian(payload[2..4], Total);
        payload[4] = (byte)MissionState;
        payload[5] = MissionMode;
        BinaryPrimitives.WriteUInt32LittleEndian(payload[6..10], MissionId);
        BinaryPrimitives.WriteUInt32LittleEndian(payload[10..14], FenceId);
        BinaryPrimitives.WriteUInt32LittleEndian(payload[14..18], RallyPointsId);
    }
}
