// <auto-generated by MavNet.CodeGen />
using System.Buffers.Binary;
using MavNet.Protocol;
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Messages;

public readonly record struct MissionItemReached(
    ushort Seq) : IMavlinkMessage<MissionItemReached>
{
    public const uint MsgId = 46u;
    public const byte CrcExtra = 11;
    public const byte MinPayloadLength = 2;
    public const byte MaxPayloadLength = 2;

    static uint IMavlinkMessage<MissionItemReached>.MsgId             => MsgId;
    static byte IMavlinkMessage<MissionItemReached>.CrcExtra          => CrcExtra;
    static byte IMavlinkMessage<MissionItemReached>.MinPayloadLength  => MinPayloadLength;
    static byte IMavlinkMessage<MissionItemReached>.MaxPayloadLength  => MaxPayloadLength;

    public static MissionItemReached Decode(System.ReadOnlySpan<byte> payload)
    {
        // MAVLink v2 senders may strip trailing zero bytes — pad up to max length.
        System.Span<byte> p = stackalloc byte[MaxPayloadLength];
        payload[..System.Math.Min(payload.Length, (int)MaxPayloadLength)].CopyTo(p);
        return new MissionItemReached(
            BinaryPrimitives.ReadUInt16LittleEndian(p[0..2]));
    }

    /// <summary>Encode the full untruncated payload. Caller may strip trailing zero bytes
    /// down to <see cref="MinPayloadLength"/> for on-wire MAVLink v2 truncation.</summary>
    public void Encode(System.Span<byte> payload)
    {
        BinaryPrimitives.WriteUInt16LittleEndian(payload[0..2], Seq);
    }
}
