// <auto-generated by MavNet.CodeGen />
using System.Buffers.Binary;
using MavNet.Protocol;
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Messages;

public readonly record struct MissionItemInt(
    float Param1,
    float Param2,
    float Param3,
    float Param4,
    int X,
    int Y,
    float Z,
    ushort Seq,
    MavCmd Command,
    byte TargetSystem,
    byte TargetComponent,
    MavFrame Frame,
    byte Current,
    byte Autocontinue,
    MavMissionType MissionType) : IMavlinkMessage<MissionItemInt>
{
    public const uint MsgId = 73u;
    public const byte CrcExtra = 38;
    public const byte MinPayloadLength = 37;
    public const byte MaxPayloadLength = 38;

    static uint IMavlinkMessage<MissionItemInt>.MsgId             => MsgId;
    static byte IMavlinkMessage<MissionItemInt>.CrcExtra          => CrcExtra;
    static byte IMavlinkMessage<MissionItemInt>.MinPayloadLength  => MinPayloadLength;
    static byte IMavlinkMessage<MissionItemInt>.MaxPayloadLength  => MaxPayloadLength;

    public static MissionItemInt Decode(System.ReadOnlySpan<byte> payload)
    {
        // MAVLink v2 senders may strip trailing zero bytes — pad up to max length.
        System.Span<byte> p = stackalloc byte[MaxPayloadLength];
        payload[..System.Math.Min(payload.Length, (int)MaxPayloadLength)].CopyTo(p);
        return new MissionItemInt(
            BinaryPrimitives.ReadSingleLittleEndian(p[0..4]),
            BinaryPrimitives.ReadSingleLittleEndian(p[4..8]),
            BinaryPrimitives.ReadSingleLittleEndian(p[8..12]),
            BinaryPrimitives.ReadSingleLittleEndian(p[12..16]),
            BinaryPrimitives.ReadInt32LittleEndian(p[16..20]),
            BinaryPrimitives.ReadInt32LittleEndian(p[20..24]),
            BinaryPrimitives.ReadSingleLittleEndian(p[24..28]),
            BinaryPrimitives.ReadUInt16LittleEndian(p[28..30]),
            (MavCmd)BinaryPrimitives.ReadUInt16LittleEndian(p[30..32]),
            p[32],
            p[33],
            (MavFrame)p[34],
            p[35],
            p[36],
            (MavMissionType)p[37]);
    }

    /// <summary>Encode the full untruncated payload. Caller may strip trailing zero bytes
    /// down to <see cref="MinPayloadLength"/> for on-wire MAVLink v2 truncation.</summary>
    public void Encode(System.Span<byte> payload)
    {
        BinaryPrimitives.WriteSingleLittleEndian(payload[0..4], Param1);
        BinaryPrimitives.WriteSingleLittleEndian(payload[4..8], Param2);
        BinaryPrimitives.WriteSingleLittleEndian(payload[8..12], Param3);
        BinaryPrimitives.WriteSingleLittleEndian(payload[12..16], Param4);
        BinaryPrimitives.WriteInt32LittleEndian(payload[16..20], X);
        BinaryPrimitives.WriteInt32LittleEndian(payload[20..24], Y);
        BinaryPrimitives.WriteSingleLittleEndian(payload[24..28], Z);
        BinaryPrimitives.WriteUInt16LittleEndian(payload[28..30], Seq);
        BinaryPrimitives.WriteUInt16LittleEndian(payload[30..32], (ushort)Command);
        payload[32] = TargetSystem;
        payload[33] = TargetComponent;
        payload[34] = (byte)Frame;
        payload[35] = Current;
        payload[36] = Autocontinue;
        payload[37] = (byte)MissionType;
    }
}
