// <auto-generated by MavNet.CodeGen />
using System.Buffers.Binary;
using MavNet.Protocol;
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Messages;

public readonly record struct MissionRequestInt(
    ushort Seq,
    byte TargetSystem,
    byte TargetComponent,
    MavMissionType MissionType) : IMavlinkMessage<MissionRequestInt>
{
    public const uint MsgId = 51u;
    public const byte CrcExtra = 196;
    public const byte MinPayloadLength = 4;
    public const byte MaxPayloadLength = 5;

    static uint IMavlinkMessage<MissionRequestInt>.MsgId             => MsgId;
    static byte IMavlinkMessage<MissionRequestInt>.CrcExtra          => CrcExtra;
    static byte IMavlinkMessage<MissionRequestInt>.MinPayloadLength  => MinPayloadLength;
    static byte IMavlinkMessage<MissionRequestInt>.MaxPayloadLength  => MaxPayloadLength;

    public static MissionRequestInt Decode(System.ReadOnlySpan<byte> payload)
    {
        // MAVLink v2 senders may strip trailing zero bytes — pad up to max length.
        System.Span<byte> p = stackalloc byte[MaxPayloadLength];
        payload[..System.Math.Min(payload.Length, (int)MaxPayloadLength)].CopyTo(p);
        return new MissionRequestInt(
            BinaryPrimitives.ReadUInt16LittleEndian(p[0..2]),
            p[2],
            p[3],
            (MavMissionType)p[4]);
    }

    /// <summary>Encode the full untruncated payload. Caller may strip trailing zero bytes
    /// down to <see cref="MinPayloadLength"/> for on-wire MAVLink v2 truncation.</summary>
    public void Encode(System.Span<byte> payload)
    {
        BinaryPrimitives.WriteUInt16LittleEndian(payload[0..2], Seq);
        payload[2] = TargetSystem;
        payload[3] = TargetComponent;
        payload[4] = (byte)MissionType;
    }
}
