// <auto-generated by MavNet.CodeGen />
using System.Buffers.Binary;
using MavNet.Protocol;
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Messages;

public readonly record struct MissionClearAll(
    byte TargetSystem,
    byte TargetComponent,
    MavMissionType MissionType) : IMavlinkMessage<MissionClearAll>
{
    public const uint MsgId = 45u;
    public const byte CrcExtra = 232;
    public const byte MinPayloadLength = 2;
    public const byte MaxPayloadLength = 3;

    static uint IMavlinkMessage<MissionClearAll>.MsgId             => MsgId;
    static byte IMavlinkMessage<MissionClearAll>.CrcExtra          => CrcExtra;
    static byte IMavlinkMessage<MissionClearAll>.MinPayloadLength  => MinPayloadLength;
    static byte IMavlinkMessage<MissionClearAll>.MaxPayloadLength  => MaxPayloadLength;

    public static MissionClearAll Decode(System.ReadOnlySpan<byte> payload)
    {
        // MAVLink v2 senders may strip trailing zero bytes — pad up to max length.
        System.Span<byte> p = stackalloc byte[MaxPayloadLength];
        payload[..System.Math.Min(payload.Length, (int)MaxPayloadLength)].CopyTo(p);
        return new MissionClearAll(
            p[0],
            p[1],
            (MavMissionType)p[2]);
    }

    /// <summary>Encode the full untruncated payload. Caller may strip trailing zero bytes
    /// down to <see cref="MinPayloadLength"/> for on-wire MAVLink v2 truncation.</summary>
    public void Encode(System.Span<byte> payload)
    {
        payload[0] = TargetSystem;
        payload[1] = TargetComponent;
        payload[2] = (byte)MissionType;
    }
}
