// <auto-generated by MavNet.CodeGen />
using System.Buffers.Binary;
using MavNet.Protocol;
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Messages;

public readonly record struct MissionAck(
    byte TargetSystem,
    byte TargetComponent,
    MavMissionResult Type,
    MavMissionType MissionType,
    uint OpaqueId) : IMavlinkMessage<MissionAck>
{
    public const uint MsgId = 47u;
    public const byte CrcExtra = 153;
    public const byte MinPayloadLength = 3;
    public const byte MaxPayloadLength = 8;

    static uint IMavlinkMessage<MissionAck>.MsgId             => MsgId;
    static byte IMavlinkMessage<MissionAck>.CrcExtra          => CrcExtra;
    static byte IMavlinkMessage<MissionAck>.MinPayloadLength  => MinPayloadLength;
    static byte IMavlinkMessage<MissionAck>.MaxPayloadLength  => MaxPayloadLength;

    public static MissionAck Decode(System.ReadOnlySpan<byte> payload)
    {
        // MAVLink v2 senders may strip trailing zero bytes — pad up to max length.
        System.Span<byte> p = stackalloc byte[MaxPayloadLength];
        payload[..System.Math.Min(payload.Length, (int)MaxPayloadLength)].CopyTo(p);
        return new MissionAck(
            p[0],
            p[1],
            (MavMissionResult)p[2],
            (MavMissionType)p[3],
            BinaryPrimitives.ReadUInt32LittleEndian(p[4..8]));
    }

    /// <summary>Encode the full untruncated payload. Caller may strip trailing zero bytes
    /// down to <see cref="MinPayloadLength"/> for on-wire MAVLink v2 truncation.</summary>
    public void Encode(System.Span<byte> payload)
    {
        payload[0] = TargetSystem;
        payload[1] = TargetComponent;
        payload[2] = (byte)Type;
        payload[3] = (byte)MissionType;
        BinaryPrimitives.WriteUInt32LittleEndian(payload[4..8], OpaqueId);
    }
}
