// <auto-generated by MavNet.CodeGen />
using System.Buffers.Binary;
using MavNet.Protocol;
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Messages;

public readonly record struct SysStatus(
    MavSysStatusSensor OnboardControlSensorsPresent,
    MavSysStatusSensor OnboardControlSensorsEnabled,
    MavSysStatusSensor OnboardControlSensorsHealth,
    ushort Load,
    ushort VoltageBattery,
    short CurrentBattery,
    ushort DropRateComm,
    ushort ErrorsComm,
    ushort ErrorsCount1,
    ushort ErrorsCount2,
    ushort ErrorsCount3,
    ushort ErrorsCount4,
    sbyte BatteryRemaining,
    MavSysStatusSensorExtended OnboardControlSensorsPresentExtended,
    MavSysStatusSensorExtended OnboardControlSensorsEnabledExtended,
    MavSysStatusSensorExtended OnboardControlSensorsHealthExtended) : IMavlinkMessage<SysStatus>
{
    public const uint MsgId = 1u;
    public const byte CrcExtra = 124;
    public const byte MinPayloadLength = 31;
    public const byte MaxPayloadLength = 43;

    static uint IMavlinkMessage<SysStatus>.MsgId             => MsgId;
    static byte IMavlinkMessage<SysStatus>.CrcExtra          => CrcExtra;
    static byte IMavlinkMessage<SysStatus>.MinPayloadLength  => MinPayloadLength;
    static byte IMavlinkMessage<SysStatus>.MaxPayloadLength  => MaxPayloadLength;

    public static SysStatus Decode(System.ReadOnlySpan<byte> payload)
    {
        // MAVLink v2 senders may strip trailing zero bytes — pad up to max length.
        System.Span<byte> p = stackalloc byte[MaxPayloadLength];
        payload[..System.Math.Min(payload.Length, (int)MaxPayloadLength)].CopyTo(p);
        return new SysStatus(
            (MavSysStatusSensor)BinaryPrimitives.ReadUInt32LittleEndian(p[0..4]),
            (MavSysStatusSensor)BinaryPrimitives.ReadUInt32LittleEndian(p[4..8]),
            (MavSysStatusSensor)BinaryPrimitives.ReadUInt32LittleEndian(p[8..12]),
            BinaryPrimitives.ReadUInt16LittleEndian(p[12..14]),
            BinaryPrimitives.ReadUInt16LittleEndian(p[14..16]),
            BinaryPrimitives.ReadInt16LittleEndian(p[16..18]),
            BinaryPrimitives.ReadUInt16LittleEndian(p[18..20]),
            BinaryPrimitives.ReadUInt16LittleEndian(p[20..22]),
            BinaryPrimitives.ReadUInt16LittleEndian(p[22..24]),
            BinaryPrimitives.ReadUInt16LittleEndian(p[24..26]),
            BinaryPrimitives.ReadUInt16LittleEndian(p[26..28]),
            BinaryPrimitives.ReadUInt16LittleEndian(p[28..30]),
            (sbyte)p[30],
            (MavSysStatusSensorExtended)BinaryPrimitives.ReadUInt32LittleEndian(p[31..35]),
            (MavSysStatusSensorExtended)BinaryPrimitives.ReadUInt32LittleEndian(p[35..39]),
            (MavSysStatusSensorExtended)BinaryPrimitives.ReadUInt32LittleEndian(p[39..43]));
    }

    /// <summary>Encode the full untruncated payload. Caller may strip trailing zero bytes
    /// down to <see cref="MinPayloadLength"/> for on-wire MAVLink v2 truncation.</summary>
    public void Encode(System.Span<byte> payload)
    {
        BinaryPrimitives.WriteUInt32LittleEndian(payload[0..4], (uint)OnboardControlSensorsPresent);
        BinaryPrimitives.WriteUInt32LittleEndian(payload[4..8], (uint)OnboardControlSensorsEnabled);
        BinaryPrimitives.WriteUInt32LittleEndian(payload[8..12], (uint)OnboardControlSensorsHealth);
        BinaryPrimitives.WriteUInt16LittleEndian(payload[12..14], Load);
        BinaryPrimitives.WriteUInt16LittleEndian(payload[14..16], VoltageBattery);
        BinaryPrimitives.WriteInt16LittleEndian(payload[16..18], CurrentBattery);
        BinaryPrimitives.WriteUInt16LittleEndian(payload[18..20], DropRateComm);
        BinaryPrimitives.WriteUInt16LittleEndian(payload[20..22], ErrorsComm);
        BinaryPrimitives.WriteUInt16LittleEndian(payload[22..24], ErrorsCount1);
        BinaryPrimitives.WriteUInt16LittleEndian(payload[24..26], ErrorsCount2);
        BinaryPrimitives.WriteUInt16LittleEndian(payload[26..28], ErrorsCount3);
        BinaryPrimitives.WriteUInt16LittleEndian(payload[28..30], ErrorsCount4);
        payload[30] = (byte)BatteryRemaining;
        BinaryPrimitives.WriteUInt32LittleEndian(payload[31..35], (uint)OnboardControlSensorsPresentExtended);
        BinaryPrimitives.WriteUInt32LittleEndian(payload[35..39], (uint)OnboardControlSensorsEnabledExtended);
        BinaryPrimitives.WriteUInt32LittleEndian(payload[39..43], (uint)OnboardControlSensorsHealthExtended);
    }
}
