// <auto-generated by MavNet.CodeGen />
using System.Buffers.Binary;
using MavNet.Protocol;
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Messages;

public readonly record struct VfrHud(
    float Airspeed,
    float Groundspeed,
    float Alt,
    float Climb,
    short Heading,
    ushort Throttle) : IMavlinkMessage<VfrHud>
{
    public const uint MsgId = 74u;
    public const byte CrcExtra = 20;
    public const byte MinPayloadLength = 20;
    public const byte MaxPayloadLength = 20;

    static uint IMavlinkMessage<VfrHud>.MsgId             => MsgId;
    static byte IMavlinkMessage<VfrHud>.CrcExtra          => CrcExtra;
    static byte IMavlinkMessage<VfrHud>.MinPayloadLength  => MinPayloadLength;
    static byte IMavlinkMessage<VfrHud>.MaxPayloadLength  => MaxPayloadLength;

    public static VfrHud Decode(System.ReadOnlySpan<byte> payload)
    {
        // MAVLink v2 senders may strip trailing zero bytes — pad up to max length.
        System.Span<byte> p = stackalloc byte[MaxPayloadLength];
        payload[..System.Math.Min(payload.Length, (int)MaxPayloadLength)].CopyTo(p);
        return new VfrHud(
            BinaryPrimitives.ReadSingleLittleEndian(p[0..4]),
            BinaryPrimitives.ReadSingleLittleEndian(p[4..8]),
            BinaryPrimitives.ReadSingleLittleEndian(p[8..12]),
            BinaryPrimitives.ReadSingleLittleEndian(p[12..16]),
            BinaryPrimitives.ReadInt16LittleEndian(p[16..18]),
            BinaryPrimitives.ReadUInt16LittleEndian(p[18..20]));
    }

    /// <summary>Encode the full untruncated payload. Caller may strip trailing zero bytes
    /// down to <see cref="MinPayloadLength"/> for on-wire MAVLink v2 truncation.</summary>
    public void Encode(System.Span<byte> payload)
    {
        BinaryPrimitives.WriteSingleLittleEndian(payload[0..4], Airspeed);
        BinaryPrimitives.WriteSingleLittleEndian(payload[4..8], Groundspeed);
        BinaryPrimitives.WriteSingleLittleEndian(payload[8..12], Alt);
        BinaryPrimitives.WriteSingleLittleEndian(payload[12..16], Climb);
        BinaryPrimitives.WriteInt16LittleEndian(payload[16..18], Heading);
        BinaryPrimitives.WriteUInt16LittleEndian(payload[18..20], Throttle);
    }
}
