// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum ActuatorConfiguration
{
    None = 0,
    Beep = 1,
    _3dModeOn = 2,
    _3dModeOff = 3,
    SpinDirection1 = 4,
    SpinDirection2 = 5,
}
