// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

[System.Flags]
public enum AisFlags
{
    PositionAccuracy = 1,
    ValidCog = 2,
    ValidVelocity = 4,
    HighVelocity = 8,
    ValidTurnRate = 16,
    TurnRateSignOnly = 32,
    ValidDimensions = 64,
    LargeBowDimension = 128,
    LargeSternDimension = 256,
    LargePortDimension = 512,
    LargeStarboardDimension = 1024,
    ValidCallsign = 2048,
    ValidName = 4096,
}
