// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum AisNavStatus
{
    UnderWay = 0,
    Anchored = 1,
    UnCommanded = 2,
    RestrictedManoeuverability = 3,
    DraughtConstrained = 4,
    Moored = 5,
    Aground = 6,
    Fishing = 7,
    Sailing = 8,
    ReservedHsc = 9,
    ReservedWig = 10,
    Reserved1 = 11,
    Reserved2 = 12,
    Reserved3 = 13,
    AisSart = 14,
    Unknown = 15,
}
