// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

[System.Flags]
public enum AttitudeTargetTypemask
{
    BodyRollRateIgnore = 1,
    BodyPitchRateIgnore = 2,
    BodyYawRateIgnore = 4,
    ThrustBodySet = 32,
    ThrottleIgnore = 64,
    AttitudeIgnore = 128,
}
