// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

[System.Flags]
public enum CameraTrackingStatusFlags
{
    Idle = 0,
    Active = 1,
    Error = 2,
    Mti = 4,
    Coasting = 8,
}
