// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum CameraZoomType
{
    ZoomTypeStep = 0,
    ZoomTypeContinuous = 1,
    ZoomTypeRange = 2,
    ZoomTypeFocalLength = 3,
    ZoomTypeHorizontalFov = 4,
}
