// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

[System.Flags]
public enum CameraCapFlags
{
    CaptureVideo = 1,
    CaptureImage = 2,
    HasModes = 4,
    CanCaptureImageInVideoMode = 8,
    CanCaptureVideoInImageMode = 16,
    HasImageSurveyMode = 32,
    HasBasicZoom = 64,
    HasBasicFocus = 128,
    HasVideoStream = 256,
    HasTrackingPoint = 512,
    HasTrackingRectangle = 1024,
    HasTrackingGeoStatus = 2048,
    HasThermalRange = 4096,
    HasMti = 8192,
}
