// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum CellularStatusFlag
{
    Unknown = 0,
    Failed = 1,
    Initializing = 2,
    Locked = 3,
    Disabled = 4,
    Disabling = 5,
    Enabling = 6,
    Enabled = 7,
    Searching = 8,
    Registered = 9,
    Disconnecting = 10,
    Connecting = 11,
    Connected = 12,
}
