// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum CellularConfigResponse
{
    Accepted = 0,
    ApnError = 1,
    PinError = 2,
    Rejected = 3,
    CellularConfigBlockedPukRequired = 4,
}
