// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

[System.Flags]
public enum ComputerStatusFlags
{
    UnderVoltage = 1,
    CpuThrottle = 2,
    ThermalThrottle = 4,
    DiskFull = 8,
}
