// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum CompMetadataType
{
    General = 0,
    Parameter = 1,
    Commands = 2,
    Peripherals = 3,
    Events = 4,
    Actuators = 5,
}
