// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum EscConnectionType
{
    Ppm = 0,
    Serial = 1,
    Oneshot = 2,
    I2c = 3,
    Can = 4,
    Dshot = 5,
}
