// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

[System.Flags]
public enum EscFailureFlags
{
    EscFailureOverCurrent = 1,
    EscFailureOverVoltage = 2,
    EscFailureOverTemperature = 4,
    EscFailureOverRpm = 8,
    EscFailureInconsistentCmd = 16,
    EscFailureMotorStuck = 32,
    EscFailureGeneric = 64,
}
