// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

[System.Flags]
public enum EstimatorStatusFlags
{
    EstimatorAttitude = 1,
    EstimatorVelocityHoriz = 2,
    EstimatorVelocityVert = 4,
    EstimatorPosHorizRel = 8,
    EstimatorPosHorizAbs = 16,
    EstimatorPosVertAbs = 32,
    EstimatorPosVertAgl = 64,
    EstimatorConstPosMode = 128,
    EstimatorPredPosHorizRel = 256,
    EstimatorPredPosHorizAbs = 512,
    EstimatorGpsGlitch = 1024,
    EstimatorAccelError = 2048,
}
