// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum FailureType
{
    Ok = 0,
    Off = 1,
    Stuck = 2,
    Garbage = 3,
    Wrong = 4,
    Slow = 5,
    Delayed = 6,
    Intermittent = 7,
}
