// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

[System.Flags]
public enum GimbalDeviceCapFlags
{
    HasRetract = 1,
    HasNeutral = 2,
    HasRollAxis = 4,
    HasRollFollow = 8,
    HasRollLock = 16,
    HasPitchAxis = 32,
    HasPitchFollow = 64,
    HasPitchLock = 128,
    HasYawAxis = 256,
    HasYawFollow = 512,
    HasYawLock = 1024,
    SupportsInfiniteYaw = 2048,
    SupportsYawInEarthFrame = 4096,
    HasRcInputs = 8192,
    CanPointLocationLocal = 65536,
    CanPointLocationGlobal = 131072,
}
