// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

[System.Flags]
public enum GimbalDeviceErrorFlags
{
    AtRollLimit = 1,
    AtPitchLimit = 2,
    AtYawLimit = 4,
    EncoderError = 8,
    PowerError = 16,
    MotorError = 32,
    SoftwareError = 64,
    CommsError = 128,
    CalibrationRunning = 256,
    NoManager = 512,
}
