// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

[System.Flags]
public enum GimbalDeviceFlags
{
    Retract = 1,
    Neutral = 2,
    RollLock = 4,
    PitchLock = 8,
    YawLock = 16,
    YawInVehicleFrame = 32,
    YawInEarthFrame = 64,
    AcceptsYawInEarthFrame = 128,
    RcExclusive = 256,
    RcMixed = 512,
}
