// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum GlobalPositionSrc
{
    Unknown = 0,
    Gnss = 1,
    Vision = 2,
    Pseudolites = 3,
    Terrain = 4,
    Magnetic = 5,
    Estimator = 6,
    Leo = 7,
}
