// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum GpsFixType
{
    NoGps = 0,
    NoFix = 1,
    _2dFix = 2,
    _3dFix = 3,
    Dgps = 4,
    RtkFloat = 5,
    RtkFixed = 6,
    Static = 7,
    Ppp = 8,
}
