// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

[System.Flags]
public enum GpsInputIgnoreFlags
{
    GpsInputIgnoreFlagAlt = 1,
    GpsInputIgnoreFlagHdop = 2,
    GpsInputIgnoreFlagVdop = 4,
    GpsInputIgnoreFlagVelHoriz = 8,
    GpsInputIgnoreFlagVelVert = 16,
    GpsInputIgnoreFlagSpeedAccuracy = 32,
    GpsInputIgnoreFlagHorizontalAccuracy = 64,
    GpsInputIgnoreFlagVerticalAccuracy = 128,
}
