// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

[System.Flags]
public enum HighresImuUpdatedFlags
{
    HighresImuUpdatedXacc = 1,
    HighresImuUpdatedYacc = 2,
    HighresImuUpdatedZacc = 4,
    HighresImuUpdatedXgyro = 8,
    HighresImuUpdatedYgyro = 16,
    HighresImuUpdatedZgyro = 32,
    HighresImuUpdatedXmag = 64,
    HighresImuUpdatedYmag = 128,
    HighresImuUpdatedZmag = 256,
    HighresImuUpdatedAbsPressure = 512,
    HighresImuUpdatedDiffPressure = 1024,
    HighresImuUpdatedPressureAlt = 2048,
    HighresImuUpdatedTemperature = 4096,
}
