// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

[System.Flags]
public enum HilSensorUpdatedFlags : uint
{
    HilSensorUpdatedXacc = 1U,
    HilSensorUpdatedYacc = 2U,
    HilSensorUpdatedZacc = 4U,
    HilSensorUpdatedXgyro = 8U,
    HilSensorUpdatedYgyro = 16U,
    HilSensorUpdatedZgyro = 32U,
    HilSensorUpdatedXmag = 64U,
    HilSensorUpdatedYmag = 128U,
    HilSensorUpdatedZmag = 256U,
    HilSensorUpdatedAbsPressure = 512U,
    HilSensorUpdatedDiffPressure = 1024U,
    HilSensorUpdatedPressureAlt = 2048U,
    HilSensorUpdatedTemperature = 4096U,
    HilSensorUpdatedReset = 2147483648U,
}
