// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

[System.Flags]
public enum HlFailureFlag
{
    Gps = 1,
    DifferentialPressure = 2,
    AbsolutePressure = 4,
    _3dAccel = 8,
    _3dGyro = 16,
    _3dMag = 32,
    Terrain = 64,
    Battery = 128,
    RcReceiver = 256,
    OffboardLink = 512,
    Engine = 1024,
    Geofence = 2048,
    Estimator = 4096,
    Mission = 8192,
}
