// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

[System.Flags]
public enum IlluminatorErrorFlags
{
    ThermalThrottling = 1,
    OverTemperatureShutdown = 2,
    ThermistorFailure = 4,
}
