// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum LandingTargetType
{
    LightBeacon = 0,
    RadioBeacon = 1,
    VisionFiducial = 2,
    VisionOther = 3,
}
