// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum MavArmAuthDeniedReason
{
    Generic = 0,
    None = 1,
    InvalidWaypoint = 2,
    Timeout = 3,
    AirspaceInUse = 4,
    BadWeather = 5,
}
