// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

[System.Flags]
public enum MavBatteryFault
{
    DeepDischarge = 1,
    Spikes = 2,
    CellFail = 4,
    OverCurrent = 8,
    OverTemperature = 16,
    UnderTemperature = 32,
    IncompatibleVoltage = 64,
    IncompatibleFirmware = 128,
    BatteryFaultIncompatibleCellsConfiguration = 256,
}
