// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum MavBatteryChargeState
{
    Undefined = 0,
    Ok = 1,
    Low = 2,
    Critical = 3,
    Emergency = 4,
    Failed = 5,
    Unhealthy = 6,
    Charging = 7,
}
