// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum MavBatteryFunction
{
    Unknown = 0,
    All = 1,
    Propulsion = 2,
    Avionics = 3,
    Payload = 4,
}
