// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum MavCollisionAction
{
    None = 0,
    Report = 1,
    AscendOrDescend = 2,
    MoveHorizontally = 3,
    MovePerpendicular = 4,
    Rtl = 5,
    Hover = 6,
}
