// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum MavDataStream
{
    All = 0,
    RawSensors = 1,
    ExtendedStatus = 2,
    RcChannels = 3,
    RawController = 4,
    Position = 6,
    Extra1 = 10,
    Extra2 = 11,
    Extra3 = 12,
}
