// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum MavDistanceSensor
{
    Laser = 0,
    Ultrasound = 1,
    Infrared = 2,
    Radar = 3,
    Unknown = 4,
}
