// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum MavEstimatorType
{
    Unknown = 0,
    Naive = 1,
    Vision = 2,
    Vio = 3,
    Gps = 4,
    GpsIns = 5,
    Mocap = 6,
    Lidar = 7,
    Autopilot = 8,
}
