// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum MavFrame
{
    Global = 0,
    LocalNed = 1,
    Mission = 2,
    GlobalRelativeAlt = 3,
    LocalEnu = 4,
    GlobalInt = 5,
    GlobalRelativeAltInt = 6,
    LocalOffsetNed = 7,
    BodyNed = 8,
    BodyOffsetNed = 9,
    GlobalTerrainAlt = 10,
    GlobalTerrainAltInt = 11,
    BodyFrd = 12,
    Reserved13 = 13,
    Reserved14 = 14,
    Reserved15 = 15,
    Reserved16 = 16,
    Reserved17 = 17,
    Reserved18 = 18,
    Reserved19 = 19,
    LocalFrd = 20,
    LocalFlu = 21,
}
