// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum MavFtpOpcode
{
    None = 0,
    Terminatesession = 1,
    Resetsession = 2,
    Listdirectory = 3,
    Openfilero = 4,
    Readfile = 5,
    Createfile = 6,
    Writefile = 7,
    Removefile = 8,
    Createdirectory = 9,
    Removedirectory = 10,
    Openfilewo = 11,
    Truncatefile = 12,
    Rename = 13,
    Calcfilecrc = 14,
    Burstreadfile = 15,
    Ack = 128,
    Nak = 129,
}
