// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum MavFtpErr
{
    None = 0,
    Fail = 1,
    Failerrno = 2,
    Invaliddatasize = 3,
    Invalidsession = 4,
    Nosessionsavailable = 5,
    Eof = 6,
    Unknowncommand = 7,
    Fileexists = 8,
    Fileprotected = 9,
    Filenotfound = 10,
}
