// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

[System.Flags]
public enum MavGeneratorStatusFlag
{
    Off = 1,
    Ready = 2,
    Generating = 4,
    Charging = 8,
    ReducedPower = 16,
    Maxpower = 32,
    OvertempWarning = 64,
    OvertempFault = 128,
    ElectronicsOvertempWarning = 256,
    ElectronicsOvertempFault = 512,
    ElectronicsFault = 1024,
    PowersourceFault = 2048,
    CommunicationWarning = 4096,
    CoolingWarning = 8192,
    PowerRailFault = 16384,
    OvercurrentFault = 32768,
    BatteryOverchargeCurrentFault = 65536,
    OvervoltageFault = 131072,
    BatteryUndervoltFault = 262144,
    StartInhibited = 524288,
    MaintenanceRequired = 1048576,
    WarmingUp = 2097152,
    Idle = 4194304,
}
