// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum MavGoto
{
    DoHold = 0,
    DoContinue = 1,
    HoldAtCurrentPosition = 2,
    HoldAtSpecifiedPosition = 3,
}
