// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum MavlinkDataStreamType
{
    MavlinkDataStreamImgJpeg = 0,
    MavlinkDataStreamImgBmp = 1,
    MavlinkDataStreamImgRaw8u = 2,
    MavlinkDataStreamImgRaw32u = 3,
    MavlinkDataStreamImgPgm = 4,
    MavlinkDataStreamImgPng = 5,
}
