// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum MavLandedState
{
    Undefined = 0,
    OnGround = 1,
    InAir = 2,
    Takeoff = 3,
    Landing = 4,
}
