// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum MavMountMode
{
    Retract = 0,
    Neutral = 1,
    MavlinkTargeting = 2,
    RcTargeting = 3,
    GpsPoint = 4,
    SysidTarget = 5,
    HomeLocation = 6,
}
