// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum MavMissionResult
{
    MavMissionAccepted = 0,
    MavMissionError = 1,
    MavMissionUnsupportedFrame = 2,
    MavMissionUnsupported = 3,
    MavMissionNoSpace = 4,
    MavMissionInvalid = 5,
    MavMissionInvalidParam1 = 6,
    MavMissionInvalidParam2 = 7,
    MavMissionInvalidParam3 = 8,
    MavMissionInvalidParam4 = 9,
    MavMissionInvalidParam5X = 10,
    MavMissionInvalidParam6Y = 11,
    MavMissionInvalidParam7 = 12,
    MavMissionInvalidSequence = 13,
    MavMissionDenied = 14,
    MavMissionOperationCancelled = 15,
}
