// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum MavMode
{
    Preflight = 0,
    StabilizeDisarmed = 80,
    StabilizeArmed = 208,
    ManualDisarmed = 64,
    ManualArmed = 192,
    GuidedDisarmed = 88,
    GuidedArmed = 216,
    AutoDisarmed = 92,
    AutoArmed = 220,
    TestDisarmed = 66,
    TestArmed = 194,
}
