// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

[System.Flags]
public enum MavModeFlagDecodePosition
{
    Safety = 128,
    Manual = 64,
    Hil = 32,
    Stabilize = 16,
    Guided = 8,
    Auto = 4,
    Test = 2,
    CustomMode = 1,
}
