// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum MavOdidSpeedAcc
{
    Unknown = 0,
    _10MetersPerSecond = 1,
    _3MetersPerSecond = 2,
    _1MetersPerSecond = 3,
    _03MetersPerSecond = 4,
}
