// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum MavOdidClassEu
{
    Undeclared = 0,
    Class0 = 1,
    Class1 = 2,
    Class2 = 3,
    Class3 = 4,
    Class4 = 5,
    Class5 = 6,
    Class6 = 7,
}
