// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum MavOdidAuthType
{
    None = 0,
    UasIdSignature = 1,
    OperatorIdSignature = 2,
    MessageSetSignature = 3,
    NetworkRemoteId = 4,
    SpecificAuthentication = 5,
}
