// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum MavOdidVerAcc
{
    Unknown = 0,
    _150Meter = 1,
    _45Meter = 2,
    _25Meter = 3,
    _10Meter = 4,
    _3Meter = 5,
    _1Meter = 6,
}
