// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum MavOdidIdType
{
    None = 0,
    SerialNumber = 1,
    CaaRegistrationId = 2,
    UtmAssignedUuid = 3,
    SpecificSessionId = 4,
}
