// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum MavOdidHorAcc
{
    Unknown = 0,
    _10nm = 1,
    _4nm = 2,
    _2nm = 3,
    _1nm = 4,
    _05nm = 5,
    _03nm = 6,
    _01nm = 7,
    _005nm = 8,
    _30Meter = 9,
    _10Meter = 10,
    _3Meter = 11,
    _1Meter = 12,
}
