// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum MavOdidTimeAcc
{
    Unknown = 0,
    _01Second = 1,
    _02Second = 2,
    _03Second = 3,
    _04Second = 4,
    _05Second = 5,
    _06Second = 6,
    _07Second = 7,
    _08Second = 8,
    _09Second = 9,
    _10Second = 10,
    _11Second = 11,
    _12Second = 12,
    _13Second = 13,
    _14Second = 14,
    _15Second = 15,
}
