// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum MavOdidStatus
{
    Undeclared = 0,
    Ground = 1,
    Airborne = 2,
    Emergency = 3,
    RemoteIdSystemFailure = 4,
}
