// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum MavParamError
{
    NoError = 0,
    DoesNotExist = 1,
    ValueOutOfRange = 2,
    PermissionDenied = 3,
    ComponentNotFound = 4,
    ReadOnly = 5,
    TypeUnsupported = 6,
    TypeMismatch = 7,
    ReadFail = 8,
}
