// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum MavParamExtType
{
    Uint8 = 1,
    Int8 = 2,
    Uint16 = 3,
    Int16 = 4,
    Uint32 = 5,
    Int32 = 6,
    Uint64 = 7,
    Int64 = 8,
    Real32 = 9,
    Real64 = 10,
    Custom = 11,
}
