// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

[System.Flags]
public enum MavPowerStatus
{
    BrickValid = 1,
    ServoValid = 2,
    UsbConnected = 4,
    PeriphOvercurrent = 8,
    PeriphHipowerOvercurrent = 16,
    Changed = 32,
}
