// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

[System.Flags]
public enum MavProtocolCapability
{
    MissionFloat = 1,
    ParamFloat = 2,
    MissionInt = 4,
    CommandInt = 8,
    ParamEncodeBytewise = 16,
    Ftp = 32,
    SetAttitudeTarget = 64,
    SetPositionTargetLocalNed = 128,
    SetPositionTargetGlobalInt = 256,
    Terrain = 512,
    Reserved3 = 1024,
    FlightTermination = 2048,
    CompassCalibration = 4096,
    Mavlink2 = 8192,
    MissionFence = 16384,
    MissionRally = 32768,
    Reserved2 = 65536,
    ParamEncodeCCast = 131072,
    ComponentImplementsGimbalManager = 262144,
    ComponentAcceptsGcsControl = 524288,
    Gripper = 1048576,
}
