// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum MavResult
{
    Accepted = 0,
    TemporarilyRejected = 1,
    Denied = 2,
    Unsupported = 3,
    Failed = 4,
    InProgress = 5,
    Cancelled = 6,
    CommandLongOnly = 7,
    CommandIntOnly = 8,
    CommandUnsupportedMavFrame = 9,
    NotInControl = 10,
}
