// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

[System.Flags]
public enum MavSysStatusSensorExtended
{
    MavSysStatusRecoverySystem = 1,
    MavSysStatusSensorLeak = 2,
}
