// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum MavStandardMode
{
    NonStandard = 0,
    PositionHold = 1,
    Orbit = 2,
    Cruise = 3,
    AltitudeHold = 4,
    SafeRecovery = 5,
    Mission = 6,
    Land = 7,
    Takeoff = 8,
}
