// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

[System.Flags]
public enum MavSysStatusSensor : uint
{
    _3dGyro = 1U,
    _3dAccel = 2U,
    _3dMag = 4U,
    AbsolutePressure = 8U,
    DifferentialPressure = 16U,
    Gps = 32U,
    OpticalFlow = 64U,
    VisionPosition = 128U,
    LaserPosition = 256U,
    ExternalGroundTruth = 512U,
    AngularRateControl = 1024U,
    AttitudeStabilization = 2048U,
    YawPosition = 4096U,
    ZAltitudeControl = 8192U,
    XyPositionControl = 16384U,
    MotorOutputs = 32768U,
    RcReceiver = 65536U,
    _3dGyro2 = 131072U,
    _3dAccel2 = 262144U,
    _3dMag2 = 524288U,
    MavSysStatusGeofence = 1048576U,
    MavSysStatusAhrs = 2097152U,
    MavSysStatusTerrain = 4194304U,
    MavSysStatusReverseMotor = 8388608U,
    MavSysStatusLogging = 16777216U,
    Battery = 33554432U,
    Proximity = 67108864U,
    Satcom = 134217728U,
    MavSysStatusPrearmCheck = 268435456U,
    MavSysStatusObstacleAvoidance = 536870912U,
    Propulsion = 1073741824U,
    MavSysStatusExtensionUsed = 2147483648U,
}
