// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum MavTunnelPayloadType
{
    Unknown = 0,
    Storm32Reserved0 = 200,
    Storm32Reserved1 = 201,
    Storm32Reserved2 = 202,
    Storm32Reserved3 = 203,
    Storm32Reserved4 = 204,
    Storm32Reserved5 = 205,
    Storm32Reserved6 = 206,
    Storm32Reserved7 = 207,
    Storm32Reserved8 = 208,
    Storm32Reserved9 = 209,
    ModalaiRemoteOsd = 210,
    ModalaiEscUartPassthru = 211,
    ModalaiIoUartPassthru = 212,
}
