// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum MavVtolState
{
    Undefined = 0,
    TransitionToFw = 1,
    TransitionToMc = 2,
    Mc = 3,
    Fw = 4,
}
