// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

[System.Flags]
public enum MavWinchStatusFlag
{
    MavWinchStatusHealthy = 1,
    MavWinchStatusFullyRetracted = 2,
    MavWinchStatusMoving = 4,
    MavWinchStatusClutchEngaged = 8,
    MavWinchStatusLocked = 16,
    MavWinchStatusDropping = 32,
    MavWinchStatusArresting = 64,
    MavWinchStatusGroundSense = 128,
    MavWinchStatusRetracting = 256,
    MavWinchStatusRedeliver = 512,
    MavWinchStatusAbandonLine = 1024,
    MavWinchStatusLocking = 2048,
    MavWinchStatusLoadLine = 4096,
    MavWinchStatusLoadPayload = 8192,
}
