// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum MissionState
{
    Unknown = 0,
    NoMission = 1,
    NotStarted = 2,
    Active = 3,
    Paused = 4,
    Complete = 5,
}
