// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum MotorTestThrottleType
{
    MotorTestThrottlePercent = 0,
    MotorTestThrottlePwm = 1,
    MotorTestThrottlePilot = 2,
    MotorTestCompassCal = 3,
}
