// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum OrbitYawBehaviour
{
    HoldFrontToCircleCenter = 0,
    HoldInitialHeading = 1,
    Uncontrolled = 2,
    HoldFrontTangentToCircle = 3,
    RcControlled = 4,
    Unchanged = 5,
}
