// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

[System.Flags]
public enum PositionTargetTypemask
{
    XIgnore = 1,
    YIgnore = 2,
    ZIgnore = 4,
    VxIgnore = 8,
    VyIgnore = 16,
    VzIgnore = 32,
    AxIgnore = 64,
    AyIgnore = 128,
    AzIgnore = 256,
    ForceSet = 512,
    YawIgnore = 1024,
    YawRateIgnore = 2048,
}
