// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum PreflightStorageMissionAction
{
    MissionReadPersistent = 0,
    MissionWritePersistent = 1,
    MissionResetDefault = 2,
}
