// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum PreflightStorageParameterAction
{
    ParamReadPersistent = 0,
    ParamWritePersistent = 1,
    ParamResetFactoryDefault = 2,
    ParamResetSensorDefault = 3,
    ParamResetAllDefault = 4,
}
