// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum PreflightCalibrationAccelerometer
{
    None = 0,
    Full = 1,
    Trim = 2,
    Temperature = 3,
    Simple = 4,
    ForceSave = 76,
}
