// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum RebootShutdownAction
{
    None = 0,
    Reboot = 1,
    Shutdown = 2,
    RebootToBootloader = 3,
    PowerOn = 4,
}
