// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

[System.Flags]
public enum SerialControlFlag
{
    Reply = 1,
    Respond = 2,
    Exclusive = 4,
    Blocking = 8,
    Multi = 16,
}
