// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum SerialControlDev
{
    Telem1 = 0,
    Telem2 = 1,
    Gps1 = 2,
    Gps2 = 3,
    Shell = 10,
    SerialControlSerial0 = 100,
    SerialControlSerial1 = 101,
    SerialControlSerial2 = 102,
    SerialControlSerial3 = 103,
    SerialControlSerial4 = 104,
    SerialControlSerial5 = 105,
    SerialControlSerial6 = 106,
    SerialControlSerial7 = 107,
    SerialControlSerial8 = 108,
    SerialControlSerial9 = 109,
}
