// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum SetFocusType
{
    FocusTypeStep = 0,
    FocusTypeContinuous = 1,
    FocusTypeRange = 2,
    FocusTypeMeters = 3,
    FocusTypeAuto = 4,
    FocusTypeAutoSingle = 5,
    FocusTypeAutoContinuous = 6,
}
