// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum StorageType
{
    Unknown = 0,
    UsbStick = 1,
    Sd = 2,
    Microsd = 3,
    Cf = 4,
    Cfe = 5,
    Xqd = 6,
    Hd = 7,
    Other = 254,
}
