// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

[System.Flags]
public enum UtmDataAvailFlags
{
    TimeValid = 1,
    UasIdAvailable = 2,
    PositionAvailable = 4,
    AltitudeAvailable = 8,
    RelativeAltitudeAvailable = 16,
    HorizontalVeloAvailable = 32,
    VerticalVeloAvailable = 64,
    NextWaypointAvailable = 128,
}
