// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum UtmFlightState
{
    Unknown = 1,
    Ground = 2,
    Airborne = 3,
    Emergency = 16,
    Noctrl = 32,
}
