// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

[System.Flags]
public enum VideoStreamStatusFlags
{
    Running = 1,
    Thermal = 2,
    ThermalRangeEnabled = 4,
}
