// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum VtolTransitionHeading
{
    VehicleDefault = 0,
    NextWaypoint = 1,
    Takeoff = 2,
    Specified = 3,
    Any = 4,
}
