// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum WifiConfigApResponse
{
    Undefined = 0,
    Accepted = 1,
    Rejected = 2,
    ModeError = 3,
    SsidError = 4,
    PasswordError = 5,
}
