// <auto-generated by MavNet.CodeGen />
namespace MavNet.Protocol.Generated.Enums;

public enum WinchActions
{
    WinchRelaxed = 0,
    WinchRelativeLengthControl = 1,
    WinchRateControl = 2,
    WinchLock = 3,
    WinchDeliver = 4,
    WinchHold = 5,
    WinchRetract = 6,
    WinchLoadLine = 7,
    WinchAbandonLine = 8,
    WinchLoadPayload = 9,
}
