// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Actuator testing command. This is similar to MAV_CMD_DO_MOTOR_TEST but operates on the level of output functions, i.e. it is possible to test Motor1 independent from which output it is configured on. Autopilots must NACK this command with MAV_RESULT_TEMPORARILY_REJECTED while armed.
/// <para>MAV_CMD entry: <c>MAV_CMD_ACTUATOR_TEST</c> (value 310).</para>
/// </summary>
public readonly record struct ActuatorTestCommand(
    float Value,
    float Timeout,
    float Param3,
    float Param4,
    ActuatorOutputFunction OutputFunction,
    float Param6,
    float Param7)
{
    public const uint CommandId = 310u;
    public const string CommandName = "MAV_CMD_ACTUATOR_TEST";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Value;
        target[1] = Timeout;
        target[2] = Param3;
        target[3] = Param4;
        target[4] = (float)(uint)OutputFunction;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static ActuatorTestCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        (ActuatorOutputFunction)(uint)source[4],
        source[5],
        source[6]);
}
