// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// If the camera supports point visual tracking (CAMERA_CAP_FLAGS_HAS_TRACKING_POINT is set), this command allows to initiate the tracking.
/// <para>MAV_CMD entry: <c>MAV_CMD_CAMERA_TRACK_POINT</c> (value 2004).</para>
/// </summary>
public readonly record struct CameraTrackPointCommand(
    float PointX,
    float PointY,
    float Radius,
    float TargetCameraID,
    float Param5,
    float Param6,
    float Param7)
{
    public const uint CommandId = 2004u;
    public const string CommandName = "MAV_CMD_CAMERA_TRACK_POINT";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = PointX;
        target[1] = PointY;
        target[2] = Radius;
        target[3] = TargetCameraID;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static CameraTrackPointCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
