// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// If the camera supports rectangle visual tracking (CAMERA_CAP_FLAGS_HAS_TRACKING_RECTANGLE is set), this command allows to initiate the tracking.
/// <para>MAV_CMD entry: <c>MAV_CMD_CAMERA_TRACK_RECTANGLE</c> (value 2005).</para>
/// </summary>
public readonly record struct CameraTrackRectangleCommand(
    float TopLeftCornerX,
    float TopLeftCornerY,
    float BottomRightCornerX,
    float BottomRightCornerY,
    float TargetCameraID,
    float Param6,
    float Param7)
{
    public const uint CommandId = 2005u;
    public const string CommandName = "MAV_CMD_CAMERA_TRACK_RECTANGLE";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = TopLeftCornerX;
        target[1] = TopLeftCornerY;
        target[2] = BottomRightCornerX;
        target[3] = BottomRightCornerY;
        target[4] = TargetCameraID;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static CameraTrackRectangleCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
