// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Reach a certain target angle.
/// <para>MAV_CMD entry: <c>MAV_CMD_CONDITION_YAW</c> (value 115).</para>
/// </summary>
public readonly record struct ConditionYawCommand(
    float Angle,
    float AngularSpeed,
    float Direction,
    MavBool Relative,
    float Param5,
    float Param6,
    float Param7)
{
    public const uint CommandId = 115u;
    public const string CommandName = "MAV_CMD_CONDITION_YAW";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Angle;
        target[1] = AngularSpeed;
        target[2] = Direction;
        target[3] = (float)(uint)Relative;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static ConditionYawCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        (MavBool)(uint)source[3],
        source[4],
        source[5],
        source[6]);
}
