// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Delay mission state machine until gate has been reached.
/// <para>MAV_CMD entry: <c>MAV_CMD_CONDITION_GATE</c> (value 4501).</para>
/// </summary>
public readonly record struct ConditionGateCommand(
    float Geometry,
    MavBool UseAltitude,
    float Param3,
    float Param4,
    float Latitude,
    float Longitude,
    float Altitude)
{
    public const uint CommandId = 4501u;
    public const string CommandName = "MAV_CMD_CONDITION_GATE";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Geometry;
        target[1] = (float)(uint)UseAltitude;
        target[2] = Param3;
        target[3] = Param4;
        target[4] = Latitude;
        target[5] = Longitude;
        target[6] = Altitude;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static ConditionGateCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        (MavBool)(uint)source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
