// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Trigger the start of an ADSB-out IDENT. This should only be used when requested to do so by an Air Traffic Controller in controlled airspace. This starts the IDENT which is then typically held for 18 seconds by the hardware per the Mode A, C, and S transponder spec.
/// <para>MAV_CMD entry: <c>MAV_CMD_DO_ADSB_OUT_IDENT</c> (value 10001).</para>
/// </summary>
public readonly record struct DoAdsbOutIdentCommand(
    float Param1,
    float Param2,
    float Param3,
    float Param4,
    float Param5,
    float Param6,
    float Param7)
{
    public const uint CommandId = 10001u;
    public const string CommandName = "MAV_CMD_DO_ADSB_OUT_IDENT";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Param1;
        target[1] = Param2;
        target[2] = Param3;
        target[3] = Param4;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static DoAdsbOutIdentCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
