// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Change speed and/or throttle set points. The value persists until it is overridden or there is a mode change
/// <para>MAV_CMD entry: <c>MAV_CMD_DO_CHANGE_SPEED</c> (value 178).</para>
/// </summary>
public readonly record struct DoChangeSpeedCommand(
    SpeedType SpeedType,
    float Speed,
    float Throttle,
    float Param4,
    float Param5,
    float Param6,
    float Param7)
{
    public const uint CommandId = 178u;
    public const string CommandName = "MAV_CMD_DO_CHANGE_SPEED";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = (float)(uint)SpeedType;
        target[1] = Speed;
        target[2] = Throttle;
        target[3] = Param4;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static DoChangeSpeedCommand Unpack(System.ReadOnlySpan<float> source) => new(
        (SpeedType)(uint)source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
