// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Change altitude set point.
/// <para>MAV_CMD entry: <c>MAV_CMD_DO_CHANGE_ALTITUDE</c> (value 186).</para>
/// </summary>
public readonly record struct DoChangeAltitudeCommand(
    float Altitude,
    MavFrame Frame,
    float Param3,
    float Param4,
    float Param5,
    float Param6,
    float Param7)
{
    public const uint CommandId = 186u;
    public const string CommandName = "MAV_CMD_DO_CHANGE_ALTITUDE";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Altitude;
        target[1] = (float)(uint)Frame;
        target[2] = Param3;
        target[3] = Param4;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static DoChangeAltitudeCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        (MavFrame)(uint)source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
