// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Configure digital camera. This is a fallback message for systems that have not yet implemented PARAM_EXT_XXX messages and camera definition files (see https://mavlink.io/en/services/camera_def.html ).
/// <para>MAV_CMD entry: <c>MAV_CMD_DO_DIGICAM_CONFIGURE</c> (value 202).</para>
/// </summary>
public readonly record struct DoDigicamConfigureCommand(
    float Mode,
    float ShutterSpeed,
    float Aperture,
    float ISO,
    float Exposure,
    float CommandIdentity,
    float EngineCutOff)
{
    public const uint CommandId = 202u;
    public const string CommandName = "MAV_CMD_DO_DIGICAM_CONFIGURE";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Mode;
        target[1] = ShutterSpeed;
        target[2] = Aperture;
        target[3] = ISO;
        target[4] = Exposure;
        target[5] = CommandIdentity;
        target[6] = EngineCutOff;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static DoDigicamConfigureCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
