// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Control digital camera. This is a fallback message for systems that have not yet implemented PARAM_EXT_XXX messages and camera definition files (see https://mavlink.io/en/services/camera_def.html ).
/// <para>MAV_CMD entry: <c>MAV_CMD_DO_DIGICAM_CONTROL</c> (value 203).</para>
/// </summary>
public readonly record struct DoDigicamControlCommand(
    float SessionControl,
    float ZoomAbsolute,
    float ZoomRelative,
    float Focus,
    float ShootCommand,
    float CommandIdentity,
    float ShotID)
{
    public const uint CommandId = 203u;
    public const string CommandName = "MAV_CMD_DO_DIGICAM_CONTROL";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = SessionControl;
        target[1] = ZoomAbsolute;
        target[2] = ZoomRelative;
        target[3] = Focus;
        target[4] = ShootCommand;
        target[5] = CommandIdentity;
        target[6] = ShotID;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static DoDigicamControlCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
