// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Control vehicle engine. This is interpreted by the vehicles engine controller to change the target engine state. It is intended for vehicles with internal combustion engines
/// <para>MAV_CMD entry: <c>MAV_CMD_DO_ENGINE_CONTROL</c> (value 223).</para>
/// </summary>
public readonly record struct DoEngineControlCommand(
    MavBool StartEngine,
    MavBool ColdStart,
    float HeightDelay,
    EngineControlOptions Options,
    float Param5,
    float Param6,
    float Param7)
{
    public const uint CommandId = 223u;
    public const string CommandName = "MAV_CMD_DO_ENGINE_CONTROL";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = (float)(uint)StartEngine;
        target[1] = (float)(uint)ColdStart;
        target[2] = HeightDelay;
        target[3] = (float)(uint)Options;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static DoEngineControlCommand Unpack(System.ReadOnlySpan<float> source) => new(
        (MavBool)(uint)source[0],
        (MavBool)(uint)source[1],
        source[2],
        (EngineControlOptions)(uint)source[3],
        source[4],
        source[5],
        source[6]);
}
