// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Enable the geofence.
/// This can be used in a mission or via the command protocol.
/// The persistence/lifetime of the setting is undefined.
/// Depending on flight stack implementation it may persist until superseded, or it may revert to a system default at the end of a mission.
/// Flight stacks typically reset the setting to system defaults on reboot.
/// <para>MAV_CMD entry: <c>MAV_CMD_DO_FENCE_ENABLE</c> (value 207).</para>
/// </summary>
public readonly record struct DoFenceEnableCommand(
    float Enable,
    FenceType Types,
    float Param3,
    float Param4,
    float Param5,
    float Param6,
    float Param7)
{
    public const uint CommandId = 207u;
    public const string CommandName = "MAV_CMD_DO_FENCE_ENABLE";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Enable;
        target[1] = (float)(uint)Types;
        target[2] = Param3;
        target[3] = Param4;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static DoFenceEnableCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        (FenceType)(uint)source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
