// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Fly a figure eight path as defined by the parameters.
/// Set parameters to NaN/INT32_MAX (as appropriate) to use system-default values.
/// The command is intended for fixed wing vehicles (and VTOL hybrids flying in fixed-wing mode), allowing POI tracking for gimbals that don't support infinite rotation.
/// This command only defines the flight path. Speed should be set independently (use e.g. MAV_CMD_DO_CHANGE_SPEED).
/// Yaw and other degrees of freedom are not specified, and will be flight-stack specific (on vehicles where they can be controlled independent of the heading).
/// <para>MAV_CMD entry: <c>MAV_CMD_DO_FIGURE_EIGHT</c> (value 35).</para>
/// </summary>
public readonly record struct DoFigureEightCommand(
    float MajorRadius,
    float MinorRadius,
    float Param3,
    float Orientation,
    float LatitudeX,
    float LongitudeY,
    float AltitudeZ)
{
    public const uint CommandId = 35u;
    public const string CommandName = "MAV_CMD_DO_FIGURE_EIGHT";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = MajorRadius;
        target[1] = MinorRadius;
        target[2] = Param3;
        target[3] = Orientation;
        target[4] = LatitudeX;
        target[5] = LongitudeY;
        target[6] = AltitudeZ;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static DoFigureEightCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
