// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Begin following a target
/// <para>MAV_CMD entry: <c>MAV_CMD_DO_FOLLOW</c> (value 32).</para>
/// </summary>
public readonly record struct DoFollowCommand(
    float SystemID,
    float Param2,
    float Param3,
    float AltitudeMode,
    float Altitude,
    float Param6,
    float TimeToLand)
{
    public const uint CommandId = 32u;
    public const string CommandName = "MAV_CMD_DO_FOLLOW";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = SystemID;
        target[1] = Param2;
        target[2] = Param3;
        target[3] = AltitudeMode;
        target[4] = Altitude;
        target[5] = Param6;
        target[6] = TimeToLand;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static DoFollowCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
