// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Reposition the MAV after a follow target command has been sent
/// <para>MAV_CMD entry: <c>MAV_CMD_DO_FOLLOW_REPOSITION</c> (value 33).</para>
/// </summary>
public readonly record struct DoFollowRepositionCommand(
    float CameraQ1,
    float CameraQ2,
    float CameraQ3,
    float CameraQ4,
    float AltitudeOffset,
    float XOffset,
    float YOffset)
{
    public const uint CommandId = 33u;
    public const string CommandName = "MAV_CMD_DO_FOLLOW_REPOSITION";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = CameraQ1;
        target[1] = CameraQ2;
        target[2] = CameraQ3;
        target[3] = CameraQ4;
        target[4] = AltitudeOffset;
        target[5] = XOffset;
        target[6] = YOffset;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static DoFollowRepositionCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
