// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Set gimbal manager pitch/yaw setpoints (low rate command). It is possible to set combinations of the values below. E.g. an angle as well as a desired angular rate can be used to get to this angle at a certain angular rate, or an angular rate only will result in continuous turning. NaN is to be used to signal unset. Note: only the gimbal manager will react to this command - it will be ignored by a gimbal device. Use GIMBAL_MANAGER_SET_PITCHYAW if you need to stream pitch/yaw setpoints at higher rate.
/// <para>MAV_CMD entry: <c>MAV_CMD_DO_GIMBAL_MANAGER_PITCHYAW</c> (value 1000).</para>
/// </summary>
public readonly record struct DoGimbalManagerPitchyawCommand(
    float PitchAngle,
    float YawAngle,
    float PitchRate,
    float YawRate,
    GimbalManagerFlags GimbalManagerFlags,
    float Param6,
    float GimbalDeviceID)
{
    public const uint CommandId = 1000u;
    public const string CommandName = "MAV_CMD_DO_GIMBAL_MANAGER_PITCHYAW";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = PitchAngle;
        target[1] = YawAngle;
        target[2] = PitchRate;
        target[3] = YawRate;
        target[4] = (float)(uint)GimbalManagerFlags;
        target[5] = Param6;
        target[6] = GimbalDeviceID;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static DoGimbalManagerPitchyawCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        (GimbalManagerFlags)(uint)source[4],
        source[5],
        source[6]);
}
