// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Gimbal configuration to set which sysid/compid is in primary and secondary control.
/// <para>MAV_CMD entry: <c>MAV_CMD_DO_GIMBAL_MANAGER_CONFIGURE</c> (value 1001).</para>
/// </summary>
public readonly record struct DoGimbalManagerConfigureCommand(
    float SysidPrimaryControl,
    float CompidPrimaryControl,
    float SysidSecondaryControl,
    float CompidSecondaryControl,
    float Param5,
    float Param6,
    float GimbalDeviceID)
{
    public const uint CommandId = 1001u;
    public const string CommandName = "MAV_CMD_DO_GIMBAL_MANAGER_CONFIGURE";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = SysidPrimaryControl;
        target[1] = CompidPrimaryControl;
        target[2] = SysidSecondaryControl;
        target[3] = CompidSecondaryControl;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = GimbalDeviceID;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static DoGimbalManagerConfigureCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
