// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Set limits for external control
/// <para>MAV_CMD entry: <c>MAV_CMD_DO_GUIDED_LIMITS</c> (value 222).</para>
/// </summary>
public readonly record struct DoGuidedLimitsCommand(
    float Timeout,
    float MinAltitude,
    float MaxAltitude,
    float HorizMoveLimit,
    float Param5,
    float Param6,
    float Param7)
{
    public const uint CommandId = 222u;
    public const string CommandName = "MAV_CMD_DO_GUIDED_LIMITS";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Timeout;
        target[1] = MinAltitude;
        target[2] = MaxAltitude;
        target[3] = HorizMoveLimit;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static DoGuidedLimitsCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
