// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Configures illuminator settings. An illuminator is a light source that is used for lighting up dark areas external to the system: e.g. a torch or searchlight (as opposed to a light source for illuminating the system itself, e.g. an indicator light).
/// <para>MAV_CMD entry: <c>MAV_CMD_DO_ILLUMINATOR_CONFIGURE</c> (value 406).</para>
/// </summary>
public readonly record struct DoIlluminatorConfigureCommand(
    IlluminatorMode Mode,
    float Brightness,
    float StrobePeriod,
    float StrobeDuty,
    float Param5,
    float Param6,
    float Param7)
{
    public const uint CommandId = 406u;
    public const string CommandName = "MAV_CMD_DO_ILLUMINATOR_CONFIGURE";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = (float)(uint)Mode;
        target[1] = Brightness;
        target[2] = StrobePeriod;
        target[3] = StrobeDuty;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static DoIlluminatorConfigureCommand Unpack(System.ReadOnlySpan<float> source) => new(
        (IlluminatorMode)(uint)source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
