// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Mission item to mark the start of a mission landing pattern, or a command to land with a mission landing pattern.
/// 
/// When used in a mission, this is a marker for the start of a sequence of mission items that represent a landing pattern.
/// It should be followed by a navigation item that defines the first waypoint of the landing sequence.
/// The start marker positional params are used only for selecting what landing pattern to use if several are defined in the mission (the selected pattern will be the one with the marker position that is closest to the vehicle when a landing is commanded).
/// If the marker item position has zero-values for latitude, longitude, and altitude, then landing pattern selection is instead based on the position of the first waypoint in the landing sequence.
/// 
/// When sent as a command it triggers a landing using a mission landing pattern.
/// The location parameters are not used in this case, and should be set to 0.
/// <para>MAV_CMD entry: <c>MAV_CMD_DO_LAND_START</c> (value 189).</para>
/// </summary>
public readonly record struct DoLandStartCommand(
    float Param1,
    float Param2,
    float Param3,
    float Param4,
    float Latitude,
    float Longitude,
    float Altitude)
{
    public const uint CommandId = 189u;
    public const string CommandName = "MAV_CMD_DO_LAND_START";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Param1;
        target[1] = Param2;
        target[2] = Param3;
        target[3] = Param4;
        target[4] = Latitude;
        target[5] = Longitude;
        target[6] = Altitude;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static DoLandStartCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
