// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Command to perform motor test.
/// <para>MAV_CMD entry: <c>MAV_CMD_DO_MOTOR_TEST</c> (value 209).</para>
/// </summary>
public readonly record struct DoMotorTestCommand(
    float Instance,
    MotorTestThrottleType ThrottleType,
    float Throttle,
    float Timeout,
    float MotorCount,
    MotorTestOrder TestOrder,
    float Param7)
{
    public const uint CommandId = 209u;
    public const string CommandName = "MAV_CMD_DO_MOTOR_TEST";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Instance;
        target[1] = (float)(uint)ThrottleType;
        target[2] = Throttle;
        target[3] = Timeout;
        target[4] = MotorCount;
        target[5] = (float)(uint)TestOrder;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static DoMotorTestCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        (MotorTestThrottleType)(uint)source[1],
        source[2],
        source[3],
        source[4],
        (MotorTestOrder)(uint)source[5],
        source[6]);
}
