// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Mission command to configure a camera or antenna mount
/// <para>MAV_CMD entry: <c>MAV_CMD_DO_MOUNT_CONFIGURE</c> (value 204).</para>
/// </summary>
public readonly record struct DoMountConfigureCommand(
    MavMountMode Mode,
    MavBool StabilizeRoll,
    MavBool StabilizePitch,
    MavBool StabilizeYaw,
    float RollInputMode,
    float PitchInputMode,
    float YawInputMode)
{
    public const uint CommandId = 204u;
    public const string CommandName = "MAV_CMD_DO_MOUNT_CONFIGURE";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = (float)(uint)Mode;
        target[1] = (float)(uint)StabilizeRoll;
        target[2] = (float)(uint)StabilizePitch;
        target[3] = (float)(uint)StabilizeYaw;
        target[4] = RollInputMode;
        target[5] = PitchInputMode;
        target[6] = YawInputMode;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static DoMountConfigureCommand Unpack(System.ReadOnlySpan<float> source) => new(
        (MavMountMode)(uint)source[0],
        (MavBool)(uint)source[1],
        (MavBool)(uint)source[2],
        (MavBool)(uint)source[3],
        source[4],
        source[5],
        source[6]);
}
