// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Mission command to control a camera or antenna mount, using a quaternion as reference.
/// <para>MAV_CMD entry: <c>MAV_CMD_DO_MOUNT_CONTROL_QUAT</c> (value 220).</para>
/// </summary>
public readonly record struct DoMountControlQuatCommand(
    float Q1,
    float Q2,
    float Q3,
    float Q4,
    float Param5,
    float Param6,
    float Param7)
{
    public const uint CommandId = 220u;
    public const string CommandName = "MAV_CMD_DO_MOUNT_CONTROL_QUAT";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Q1;
        target[1] = Q2;
        target[2] = Q3;
        target[3] = Q4;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static DoMountControlQuatCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
