// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Mission command to control a camera or antenna mount
/// <para>MAV_CMD entry: <c>MAV_CMD_DO_MOUNT_CONTROL</c> (value 205).</para>
/// </summary>
public readonly record struct DoMountControlCommand(
    float Pitch,
    float Roll,
    float Yaw,
    float Altitude,
    float Latitude,
    float Longitude,
    MavMountMode Mode)
{
    public const uint CommandId = 205u;
    public const string CommandName = "MAV_CMD_DO_MOUNT_CONTROL";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Pitch;
        target[1] = Roll;
        target[2] = Yaw;
        target[3] = Altitude;
        target[4] = Latitude;
        target[5] = Longitude;
        target[6] = (float)(uint)Mode;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static DoMountControlCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        (MavMountMode)(uint)source[6]);
}
