// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Start orbiting on the circumference of a circle defined by the parameters. Setting values to NaN/INT32_MAX (as appropriate) results in using defaults.
/// <para>MAV_CMD entry: <c>MAV_CMD_DO_ORBIT</c> (value 34).</para>
/// </summary>
public readonly record struct DoOrbitCommand(
    float Radius,
    float Velocity,
    OrbitYawBehaviour YawBehavior,
    float Orbits,
    float LatitudeX,
    float LongitudeY,
    float AltitudeZ)
{
    public const uint CommandId = 34u;
    public const string CommandName = "MAV_CMD_DO_ORBIT";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Radius;
        target[1] = Velocity;
        target[2] = (float)(uint)YawBehavior;
        target[3] = Orbits;
        target[4] = LatitudeX;
        target[5] = LongitudeY;
        target[6] = AltitudeZ;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static DoOrbitCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        (OrbitYawBehaviour)(uint)source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
