// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Mission item to specify the start of a failsafe/landing return-path segment (the end of the segment is the next MAV_CMD_DO_LAND_START item).
/// A vehicle that is using missions for landing (e.g. in a return mode) will join the mission on the closest path of the return-path segment (instead of MAV_CMD_DO_LAND_START or the nearest waypoint).
/// The main use case is to minimize the failsafe flight path in corridor missions, where the inbound/outbound paths are constrained (by geofences) to the same particular path.
/// The MAV_CMD_NAV_RETURN_PATH_START would be placed at the start of the return path.
/// If a failsafe occurs on the outbound path the vehicle will move to the nearest point on the return path (which is parallel for this kind of mission), effectively turning round and following the shortest path to landing.
/// If a failsafe occurs on the inbound path the vehicle is already on the return segment and will continue to landing.
/// The Latitude/Longitude/Altitude are optional, and may be set to 0 if not needed.
/// If specified, the item defines the waypoint at which the return segment starts.
/// If sent using as a command, the vehicle will perform a mission landing (using the land segment if defined) or reject the command if mission landings are not supported, or no mission landing is defined. When used as a command any position information in the command is ignored.
/// <para>MAV_CMD entry: <c>MAV_CMD_DO_RETURN_PATH_START</c> (value 188).</para>
/// </summary>
public readonly record struct DoReturnPathStartCommand(
    float Param1,
    float Param2,
    float Param3,
    float Param4,
    float Latitude,
    float Longitude,
    float Altitude)
{
    public const uint CommandId = 188u;
    public const string CommandName = "MAV_CMD_DO_RETURN_PATH_START";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Param1;
        target[1] = Param2;
        target[2] = Param3;
        target[3] = Param4;
        target[4] = Latitude;
        target[5] = Longitude;
        target[6] = Altitude;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static DoReturnPathStartCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
