// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Cycle a between its nominal setting and a desired PWM for a desired number of cycles with a desired period.
/// <para>MAV_CMD entry: <c>MAV_CMD_DO_REPEAT_SERVO</c> (value 184).</para>
/// </summary>
public readonly record struct DoRepeatServoCommand(
    float Instance,
    float PWM,
    float Count,
    float Time,
    float Param5,
    float Param6,
    float Param7)
{
    public const uint CommandId = 184u;
    public const string CommandName = "MAV_CMD_DO_REPEAT_SERVO";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Instance;
        target[1] = PWM;
        target[2] = Count;
        target[3] = Time;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static DoRepeatServoCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
