// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Reposition the vehicle to a specific WGS84 global position. This command is intended for guided commands (for missions use MAV_CMD_NAV_WAYPOINT instead).
/// <para>MAV_CMD entry: <c>MAV_CMD_DO_REPOSITION</c> (value 192).</para>
/// </summary>
public readonly record struct DoRepositionCommand(
    float Speed,
    MavDoRepositionFlags Bitmask,
    float Radius,
    float Yaw,
    float Latitude,
    float Longitude,
    float Altitude)
{
    public const uint CommandId = 192u;
    public const string CommandName = "MAV_CMD_DO_REPOSITION";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Speed;
        target[1] = (float)(uint)Bitmask;
        target[2] = Radius;
        target[3] = Yaw;
        target[4] = Latitude;
        target[5] = Longitude;
        target[6] = Altitude;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static DoRepositionCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        (MavDoRepositionFlags)(uint)source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
