// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Set a system parameter.  Caution!  Use of this command requires knowledge of the numeric enumeration value of the parameter.
/// <para>MAV_CMD entry: <c>MAV_CMD_DO_SET_PARAMETER</c> (value 180).</para>
/// </summary>
public readonly record struct DoSetParameterCommand(
    float Number,
    float Value,
    float Param3,
    float Param4,
    float Param5,
    float Param6,
    float Param7)
{
    public const uint CommandId = 180u;
    public const string CommandName = "MAV_CMD_DO_SET_PARAMETER";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Number;
        target[1] = Value;
        target[2] = Param3;
        target[3] = Param4;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static DoSetParameterCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
