// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Mission command to set camera trigger interval for this flight. If triggering is enabled, the camera is triggered each time this interval expires. This command can also be used to set the shutter integration time for the camera.
/// <para>MAV_CMD entry: <c>MAV_CMD_DO_SET_CAM_TRIGG_INTERVAL</c> (value 214).</para>
/// </summary>
public readonly record struct DoSetCamTriggIntervalCommand(
    float TriggerCycle,
    float ShutterIntegration,
    float TargetCameraID,
    float Param4,
    float Param5,
    float Param6,
    float Param7)
{
    public const uint CommandId = 214u;
    public const string CommandName = "MAV_CMD_DO_SET_CAM_TRIGG_INTERVAL";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = TriggerCycle;
        target[1] = ShutterIntegration;
        target[2] = TargetCameraID;
        target[3] = Param4;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static DoSetCamTriggIntervalCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
