// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Sets the home position to either to the current position or a specified position.
/// The home position is the default position that the system will return to and land on.
/// The position is set automatically by the system during the takeoff (and may also be set using this command).
/// Note: the current home position may be emitted in a HOME_POSITION message on request (using MAV_CMD_REQUEST_MESSAGE with param1=242).
/// <para>MAV_CMD entry: <c>MAV_CMD_DO_SET_HOME</c> (value 179).</para>
/// </summary>
public readonly record struct DoSetHomeCommand(
    MavBool UseCurrent,
    float Roll,
    float Pitch,
    float Yaw,
    float Latitude,
    float Longitude,
    float Altitude)
{
    public const uint CommandId = 179u;
    public const string CommandName = "MAV_CMD_DO_SET_HOME";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = (float)(uint)UseCurrent;
        target[1] = Roll;
        target[2] = Pitch;
        target[3] = Yaw;
        target[4] = Latitude;
        target[5] = Longitude;
        target[6] = Altitude;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static DoSetHomeCommand Unpack(System.ReadOnlySpan<float> source) => new(
        (MavBool)(uint)source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
