// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Mission command to set camera trigger distance for this flight. The camera is triggered each time this distance is exceeded. This command can also be used to set the shutter integration time for the camera.
/// <para>MAV_CMD entry: <c>MAV_CMD_DO_SET_CAM_TRIGG_DIST</c> (value 206).</para>
/// </summary>
public readonly record struct DoSetCamTriggDistCommand(
    float Distance,
    float Shutter,
    MavBool Trigger,
    float TargetCameraID,
    float Param5,
    float Param6,
    float Param7)
{
    public const uint CommandId = 206u;
    public const string CommandName = "MAV_CMD_DO_SET_CAM_TRIGG_DIST";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Distance;
        target[1] = Shutter;
        target[2] = (float)(uint)Trigger;
        target[3] = TargetCameraID;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static DoSetCamTriggDistCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        (MavBool)(uint)source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
