// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Enable the specified standard MAVLink mode.
/// If the specified mode is not supported, the vehicle should ACK with MAV_RESULT_FAILED.
/// See https://mavlink.io/en/services/standard_modes.html
/// <para>MAV_CMD entry: <c>MAV_CMD_DO_SET_STANDARD_MODE</c> (value 262).</para>
/// </summary>
public readonly record struct DoSetStandardModeCommand(
    MavStandardMode StandardMode,
    float Param2,
    float Param3,
    float Param4,
    float Param5,
    float Param6,
    float Param7)
{
    public const uint CommandId = 262u;
    public const string CommandName = "MAV_CMD_DO_SET_STANDARD_MODE";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = (float)(uint)StandardMode;
        target[1] = Param2;
        target[2] = Param3;
        target[3] = Param4;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static DoSetStandardModeCommand Unpack(System.ReadOnlySpan<float> source) => new(
        (MavStandardMode)(uint)source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
