// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Set the mission item with sequence number seq as the current item and emit MISSION_CURRENT (whether or not the mission number changed).
/// If a mission is currently being executed, the system will continue to this new mission item on the shortest path, skipping any intermediate mission items.
/// Note that mission jump repeat counters are not reset unless param2 is set (see MAV_CMD_DO_JUMP param2).
/// 
/// This command may trigger a mission state-machine change on some systems: for example from MISSION_STATE_NOT_STARTED or MISSION_STATE_PAUSED to MISSION_STATE_ACTIVE.
/// If the system is in mission mode, on those systems this command might therefore start, restart or resume the mission.
/// If the system is not in mission mode this command must not trigger a switch to mission mode.
/// 
/// The mission may be "reset" using param2.
/// Resetting sets jump counters to initial values (to reset counters without changing the current mission item set the param1 to `-1`).
/// Resetting also explicitly changes a mission state of MISSION_STATE_COMPLETE to MISSION_STATE_PAUSED or MISSION_STATE_ACTIVE, potentially allowing it to resume when it is (next) in a mission mode.
/// 
/// The command will ACK with MAV_RESULT_FAILED if the sequence number is out of range (including if there is no mission item).
/// <para>MAV_CMD entry: <c>MAV_CMD_DO_SET_MISSION_CURRENT</c> (value 224).</para>
/// </summary>
public readonly record struct DoSetMissionCurrentCommand(
    float Number,
    MavBool ResetMission,
    float Param3,
    float Param4,
    float Param5,
    float Param6,
    float Param7)
{
    public const uint CommandId = 224u;
    public const string CommandName = "MAV_CMD_DO_SET_MISSION_CURRENT";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Number;
        target[1] = (float)(uint)ResetMission;
        target[2] = Param3;
        target[3] = Param4;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static DoSetMissionCurrentCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        (MavBool)(uint)source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
