// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Sets the region of interest (ROI) to be toward next waypoint, with optional pitch/roll/yaw offset. This can then be used by the vehicle's control system to control the vehicle attitude and the attitude of various sensors such as cameras. This command can be sent to a gimbal manager but not to a gimbal device. A gimbal device is not to react to this message.
/// <para>MAV_CMD entry: <c>MAV_CMD_DO_SET_ROI_WPNEXT_OFFSET</c> (value 196).</para>
/// </summary>
public readonly record struct DoSetRoiWpnextOffsetCommand(
    float GimbalDeviceID,
    float Param2,
    float Param3,
    float Param4,
    float PitchOffset,
    float RollOffset,
    float YawOffset)
{
    public const uint CommandId = 196u;
    public const string CommandName = "MAV_CMD_DO_SET_ROI_WPNEXT_OFFSET";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = GimbalDeviceID;
        target[1] = Param2;
        target[2] = Param3;
        target[3] = Param4;
        target[4] = PitchOffset;
        target[5] = RollOffset;
        target[6] = YawOffset;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static DoSetRoiWpnextOffsetCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
