// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Sets actuators (e.g. servos) to a desired value. The actuator numbers are mapped to specific outputs (e.g. on any MAIN or AUX PWM or UAVCAN) using a flight-stack specific mechanism (i.e. a parameter).
/// <para>MAV_CMD entry: <c>MAV_CMD_DO_SET_ACTUATOR</c> (value 187).</para>
/// </summary>
public readonly record struct DoSetActuatorCommand(
    float Actuator1,
    float Actuator2,
    float Actuator3,
    float Actuator4,
    float Actuator5,
    float Actuator6,
    float Index)
{
    public const uint CommandId = 187u;
    public const string CommandName = "MAV_CMD_DO_SET_ACTUATOR";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Actuator1;
        target[1] = Actuator2;
        target[2] = Actuator3;
        target[3] = Actuator4;
        target[4] = Actuator5;
        target[5] = Actuator6;
        target[6] = Index;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static DoSetActuatorCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
