// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Set system mode.
/// <para>MAV_CMD entry: <c>MAV_CMD_DO_SET_MODE</c> (value 176).</para>
/// </summary>
public readonly record struct DoSetModeCommand(
    MavModeFlag Mode,
    float CustomMode,
    float CustomSubmode,
    float Param4,
    float Param5,
    float Param6,
    float Param7)
{
    public const uint CommandId = 176u;
    public const string CommandName = "MAV_CMD_DO_SET_MODE";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = (float)(uint)Mode;
        target[1] = CustomMode;
        target[2] = CustomSubmode;
        target[3] = Param4;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static DoSetModeCommand Unpack(System.ReadOnlySpan<float> source) => new(
        (MavModeFlag)(uint)source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
