// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Enable or disable on-board camera triggering system.
/// <para>MAV_CMD entry: <c>MAV_CMD_DO_TRIGGER_CONTROL</c> (value 2003).</para>
/// </summary>
public readonly record struct DoTriggerControlCommand(
    float Enable,
    float Reset,
    float Pause,
    float TargetCameraID,
    float Param5,
    float Param6,
    float Param7)
{
    public const uint CommandId = 2003u;
    public const string CommandName = "MAV_CMD_DO_TRIGGER_CONTROL";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Enable;
        target[1] = Reset;
        target[2] = Pause;
        target[3] = TargetCameraID;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static DoTriggerControlCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
