// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Command to operate winch.
/// <para>MAV_CMD entry: <c>MAV_CMD_DO_WINCH</c> (value 42600).</para>
/// </summary>
public readonly record struct DoWinchCommand(
    float Instance,
    WinchActions Action,
    float Length,
    float Rate,
    float Param5,
    float Param6,
    float Param7)
{
    public const uint CommandId = 42600u;
    public const string CommandName = "MAV_CMD_DO_WINCH";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Instance;
        target[1] = (float)(uint)Action;
        target[2] = Length;
        target[3] = Rate;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static DoWinchCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        (WinchActions)(uint)source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
