// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Provide an external position estimate for use when dead-reckoning. This is meant to be used for occasional position resets that may be provided by a external system such as a remote pilot using landmarks over a video link.
/// <para>MAV_CMD entry: <c>MAV_CMD_EXTERNAL_POSITION_ESTIMATE</c> (value 43003).</para>
/// </summary>
public readonly record struct ExternalPositionEstimateCommand(
    float TransmissionTime,
    float ProcessingTime,
    float Accuracy,
    float Param4,
    float Latitude,
    float Longitude,
    float Altitude)
{
    public const uint CommandId = 43003u;
    public const string CommandName = "MAV_CMD_EXTERNAL_POSITION_ESTIMATE";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = TransmissionTime;
        target[1] = ProcessingTime;
        target[2] = Accuracy;
        target[3] = Param4;
        target[4] = Latitude;
        target[5] = Longitude;
        target[6] = Altitude;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static ExternalPositionEstimateCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
