// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Magnetometer calibration based on provided known yaw. This allows for fast calibration using WMM field tables in the vehicle, given only the known yaw of the vehicle. If Latitude and longitude are both zero then use the current vehicle location.
/// <para>MAV_CMD entry: <c>MAV_CMD_FIXED_MAG_CAL_YAW</c> (value 42006).</para>
/// </summary>
public readonly record struct FixedMagCalYawCommand(
    float Yaw,
    float CompassMask,
    float Latitude,
    float Longitude,
    float Param5,
    float Param6,
    float Param7)
{
    public const uint CommandId = 42006u;
    public const string CommandName = "MAV_CMD_FIXED_MAG_CAL_YAW";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Yaw;
        target[1] = CompassMask;
        target[2] = Latitude;
        target[3] = Longitude;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static FixedMagCalYawCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
