// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Request the interval between messages for a particular MAVLink message ID.
/// The receiver should ACK the command and then emit its response in a MESSAGE_INTERVAL message.
/// <para>MAV_CMD entry: <c>MAV_CMD_GET_MESSAGE_INTERVAL</c> (value 510).</para>
/// </summary>
public readonly record struct GetMessageIntervalCommand(
    float MessageID,
    float Param2,
    float Param3,
    float Param4,
    float Param5,
    float Param6,
    float Param7)
{
    public const uint CommandId = 510u;
    public const string CommandName = "MAV_CMD_GET_MESSAGE_INTERVAL";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = MessageID;
        target[1] = Param2;
        target[2] = Param3;
        target[3] = Param4;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static GetMessageIntervalCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
