// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Turns illuminators ON/OFF. An illuminator is a light source that is used for lighting up dark areas external to the system: e.g. a torch or searchlight (as opposed to a light source for illuminating the system itself, e.g. an indicator light).
/// <para>MAV_CMD entry: <c>MAV_CMD_ILLUMINATOR_ON_OFF</c> (value 405).</para>
/// </summary>
public readonly record struct IlluminatorOnOffCommand(
    MavBool Enable,
    float Param2,
    float Param3,
    float Param4,
    float Param5,
    float Param6,
    float Param7)
{
    public const uint CommandId = 405u;
    public const string CommandName = "MAV_CMD_ILLUMINATOR_ON_OFF";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = (float)(uint)Enable;
        target[1] = Param2;
        target[2] = Param3;
        target[3] = Param4;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static IlluminatorOnOffCommand Unpack(System.ReadOnlySpan<float> source) => new(
        (MavBool)(uint)source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
