// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Inject artificial failure for testing purposes. Note that autopilots should implement an additional protection before accepting this command such as a specific param setting.
/// <para>MAV_CMD entry: <c>MAV_CMD_INJECT_FAILURE</c> (value 420).</para>
/// </summary>
public readonly record struct InjectFailureCommand(
    FailureUnit FailureUnit,
    FailureType FailureType,
    float Instance,
    float Param4,
    float Param5,
    float Param6,
    float Param7)
{
    public const uint CommandId = 420u;
    public const string CommandName = "MAV_CMD_INJECT_FAILURE";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = (float)(uint)FailureUnit;
        target[1] = (float)(uint)FailureType;
        target[2] = Instance;
        target[3] = Param4;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static InjectFailureCommand Unpack(System.ReadOnlySpan<float> source) => new(
        (FailureUnit)(uint)source[0],
        (FailureType)(uint)source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
