// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Circular arc path waypoint.
/// This defines the end/exit point and angle (param1) of an arc path from the previous waypoint. A position is required before this command to define the start of the arc (e.g. current position, a MAV_CMD_NAV_WAYPOINT, or a MAV_CMD_NAV_ARC_WAYPOINT).
/// The resulting path is a circular arc in the NE frame, with the difference in height being defined by the difference in waypoint altitudes.
/// <para>MAV_CMD entry: <c>MAV_CMD_NAV_ARC_WAYPOINT</c> (value 36).</para>
/// </summary>
public readonly record struct NavArcWaypointCommand(
    float ArcAngle,
    float Param2,
    float Param3,
    float Param4,
    float Latitude,
    float Longitude,
    float Altitude)
{
    public const uint CommandId = 36u;
    public const string CommandName = "MAV_CMD_NAV_ARC_WAYPOINT";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = ArcAngle;
        target[1] = Param2;
        target[2] = Param3;
        target[3] = Param4;
        target[4] = Latitude;
        target[5] = Longitude;
        target[6] = Altitude;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static NavArcWaypointCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
