// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Continue on the current course and climb/descend to specified altitude.  When the altitude is reached continue to the next command (i.e., don't proceed to the next command until the desired altitude is reached.
/// <para>MAV_CMD entry: <c>MAV_CMD_NAV_CONTINUE_AND_CHANGE_ALT</c> (value 30).</para>
/// </summary>
public readonly record struct NavContinueAndChangeAltCommand(
    float Action,
    float Param2,
    float Param3,
    float Param4,
    float Param5,
    float Param6,
    float Altitude)
{
    public const uint CommandId = 30u;
    public const string CommandName = "MAV_CMD_NAV_CONTINUE_AND_CHANGE_ALT";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Action;
        target[1] = Param2;
        target[2] = Param3;
        target[3] = Param4;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = Altitude;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static NavContinueAndChangeAltCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
