// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Delay the next navigation command a number of seconds or until a specified time
/// <para>MAV_CMD entry: <c>MAV_CMD_NAV_DELAY</c> (value 93).</para>
/// </summary>
public readonly record struct NavDelayCommand(
    float Delay,
    float Hour,
    float Minute,
    float Second,
    float Param5,
    float Param6,
    float Param7)
{
    public const uint CommandId = 93u;
    public const string CommandName = "MAV_CMD_NAV_DELAY";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Delay;
        target[1] = Hour;
        target[2] = Minute;
        target[3] = Second;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static NavDelayCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
