// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Circular fence area. The vehicle must stay inside this area.
/// <para>MAV_CMD entry: <c>MAV_CMD_NAV_FENCE_CIRCLE_INCLUSION</c> (value 5003).</para>
/// </summary>
public readonly record struct NavFenceCircleInclusionCommand(
    float Radius,
    float InclusionGroup,
    float Param3,
    float Param4,
    float Latitude,
    float Longitude,
    float Param7)
{
    public const uint CommandId = 5003u;
    public const string CommandName = "MAV_CMD_NAV_FENCE_CIRCLE_INCLUSION";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Radius;
        target[1] = InclusionGroup;
        target[2] = Param3;
        target[3] = Param4;
        target[4] = Latitude;
        target[5] = Longitude;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static NavFenceCircleInclusionCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
