// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Vehicle following, i.e. this waypoint represents the position of a moving vehicle
/// <para>MAV_CMD entry: <c>MAV_CMD_NAV_FOLLOW</c> (value 25).</para>
/// </summary>
public readonly record struct NavFollowCommand(
    float Following,
    float GroundSpeed,
    float Radius,
    float Yaw,
    float Latitude,
    float Longitude,
    float Altitude)
{
    public const uint CommandId = 25u;
    public const string CommandName = "MAV_CMD_NAV_FOLLOW";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Following;
        target[1] = GroundSpeed;
        target[2] = Radius;
        target[3] = Yaw;
        target[4] = Latitude;
        target[5] = Longitude;
        target[6] = Altitude;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static NavFollowCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
