// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Loiter around this waypoint an unlimited amount of time
/// <para>MAV_CMD entry: <c>MAV_CMD_NAV_LOITER_UNLIM</c> (value 17).</para>
/// </summary>
public readonly record struct NavLoiterUnlimCommand(
    float Param1,
    float Param2,
    float Radius,
    float Yaw,
    float Latitude,
    float Longitude,
    float Altitude)
{
    public const uint CommandId = 17u;
    public const string CommandName = "MAV_CMD_NAV_LOITER_UNLIM";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Param1;
        target[1] = Param2;
        target[2] = Radius;
        target[3] = Yaw;
        target[4] = Latitude;
        target[5] = Longitude;
        target[6] = Altitude;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static NavLoiterUnlimCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
