// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Land at location.
/// <para>MAV_CMD entry: <c>MAV_CMD_NAV_LAND</c> (value 21).</para>
/// </summary>
public readonly record struct NavLandCommand(
    float AbortAlt,
    PrecisionLandMode LandMode,
    float Param3,
    float YawAngle,
    float Latitude,
    float Longitude,
    float Altitude)
{
    public const uint CommandId = 21u;
    public const string CommandName = "MAV_CMD_NAV_LAND";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = AbortAlt;
        target[1] = (float)(uint)LandMode;
        target[2] = Param3;
        target[3] = YawAngle;
        target[4] = Latitude;
        target[5] = Longitude;
        target[6] = Altitude;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static NavLandCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        (PrecisionLandMode)(uint)source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
