// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Loiter at the specified latitude, longitude and altitude for a certain amount of time. Multicopter vehicles stop at the point (within a vehicle-specific acceptance radius). Forward-only moving vehicles (e.g. fixed-wing) circle the point with the specified radius/direction. If the Heading Required parameter (2) is non-zero forward moving aircraft will only leave the loiter circle once heading towards the next waypoint.
/// <para>MAV_CMD entry: <c>MAV_CMD_NAV_LOITER_TIME</c> (value 19).</para>
/// </summary>
public readonly record struct NavLoiterTimeCommand(
    float Time,
    MavBool HeadingRequired,
    float Radius,
    float XtrackLocation,
    float Latitude,
    float Longitude,
    float Altitude)
{
    public const uint CommandId = 19u;
    public const string CommandName = "MAV_CMD_NAV_LOITER_TIME";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Time;
        target[1] = (float)(uint)HeadingRequired;
        target[2] = Radius;
        target[3] = XtrackLocation;
        target[4] = Latitude;
        target[5] = Longitude;
        target[6] = Altitude;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static NavLoiterTimeCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        (MavBool)(uint)source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
