// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Land at local position (local frame only)
/// <para>MAV_CMD entry: <c>MAV_CMD_NAV_LAND_LOCAL</c> (value 23).</para>
/// </summary>
public readonly record struct NavLandLocalCommand(
    float Target,
    float Offset,
    float DescendRate,
    float Yaw,
    float YPosition,
    float XPosition,
    float ZPosition)
{
    public const uint CommandId = 23u;
    public const string CommandName = "MAV_CMD_NAV_LAND_LOCAL";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Target;
        target[1] = Offset;
        target[2] = DescendRate;
        target[3] = Yaw;
        target[4] = YPosition;
        target[5] = XPosition;
        target[6] = ZPosition;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static NavLandLocalCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
