// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Loiter around this waypoint for X turns
/// <para>MAV_CMD entry: <c>MAV_CMD_NAV_LOITER_TURNS</c> (value 18).</para>
/// </summary>
public readonly record struct NavLoiterTurnsCommand(
    float Turns,
    MavBool HeadingRequired,
    float Radius,
    float XtrackLocation,
    float Latitude,
    float Longitude,
    float Altitude)
{
    public const uint CommandId = 18u;
    public const string CommandName = "MAV_CMD_NAV_LOITER_TURNS";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Turns;
        target[1] = (float)(uint)HeadingRequired;
        target[2] = Radius;
        target[3] = XtrackLocation;
        target[4] = Latitude;
        target[5] = Longitude;
        target[6] = Altitude;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static NavLoiterTurnsCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        (MavBool)(uint)source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
