// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Begin loiter at the specified Latitude and Longitude.  If Lat=Lon=0, then loiter at the current position.  Don't consider the navigation command complete (don't leave loiter) until the altitude has been reached. Additionally, if the Heading Required parameter is non-zero the aircraft will not leave the loiter until heading toward the next waypoint.
/// <para>MAV_CMD entry: <c>MAV_CMD_NAV_LOITER_TO_ALT</c> (value 31).</para>
/// </summary>
public readonly record struct NavLoiterToAltCommand(
    MavBool HeadingRequired,
    float Radius,
    float Param3,
    float XtrackLocation,
    float Latitude,
    float Longitude,
    float Altitude)
{
    public const uint CommandId = 31u;
    public const string CommandName = "MAV_CMD_NAV_LOITER_TO_ALT";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = (float)(uint)HeadingRequired;
        target[1] = Radius;
        target[2] = Param3;
        target[3] = XtrackLocation;
        target[4] = Latitude;
        target[5] = Longitude;
        target[6] = Altitude;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static NavLoiterToAltCommand Unpack(System.ReadOnlySpan<float> source) => new(
        (MavBool)(uint)source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
