// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Control autonomous path planning on the MAV.
/// <para>MAV_CMD entry: <c>MAV_CMD_NAV_PATHPLANNING</c> (value 81).</para>
/// </summary>
public readonly record struct NavPathplanningCommand(
    float LocalCtrl,
    float GlobalCtrl,
    float Param3,
    float Yaw,
    float LatitudeX,
    float LongitudeY,
    float AltitudeZ)
{
    public const uint CommandId = 81u;
    public const string CommandName = "MAV_CMD_NAV_PATHPLANNING";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = LocalCtrl;
        target[1] = GlobalCtrl;
        target[2] = Param3;
        target[3] = Yaw;
        target[4] = LatitudeX;
        target[5] = LongitudeY;
        target[6] = AltitudeZ;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static NavPathplanningCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
