// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Sets the region of interest (ROI) for a sensor set or the vehicle itself. This can then be used by the vehicle's control system to control the vehicle attitude and the attitude of various sensors such as cameras.
/// <para>MAV_CMD entry: <c>MAV_CMD_NAV_ROI</c> (value 80).</para>
/// </summary>
public readonly record struct NavRoiCommand(
    MavRoi ROIMode,
    float WPIndex,
    float ROIIndex,
    float Param4,
    float X,
    float Y,
    float Z)
{
    public const uint CommandId = 80u;
    public const string CommandName = "MAV_CMD_NAV_ROI";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = (float)(uint)ROIMode;
        target[1] = WPIndex;
        target[2] = ROIIndex;
        target[3] = Param4;
        target[4] = X;
        target[5] = Y;
        target[6] = Z;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static NavRoiCommand Unpack(System.ReadOnlySpan<float> source) => new(
        (MavRoi)(uint)source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
