// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Sets a desired vehicle turn angle and speed change.
/// <para>MAV_CMD entry: <c>MAV_CMD_NAV_SET_YAW_SPEED</c> (value 213).</para>
/// </summary>
public readonly record struct NavSetYawSpeedCommand(
    float Yaw,
    float Speed,
    MavBool Angle,
    float Param4,
    float Param5,
    float Param6,
    float Param7)
{
    public const uint CommandId = 213u;
    public const string CommandName = "MAV_CMD_NAV_SET_YAW_SPEED";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Yaw;
        target[1] = Speed;
        target[2] = (float)(uint)Angle;
        target[3] = Param4;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static NavSetYawSpeedCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        (MavBool)(uint)source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
