// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Takeoff from ground / hand. Vehicles that support multiple takeoff modes (e.g. VTOL quadplane) should take off using the currently configured mode.
/// <para>MAV_CMD entry: <c>MAV_CMD_NAV_TAKEOFF</c> (value 22).</para>
/// </summary>
public readonly record struct NavTakeoffCommand(
    float Pitch,
    float Param2,
    NavTakeoffFlags Flags,
    float Yaw,
    float Latitude,
    float Longitude,
    float Altitude)
{
    public const uint CommandId = 22u;
    public const string CommandName = "MAV_CMD_NAV_TAKEOFF";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Pitch;
        target[1] = Param2;
        target[2] = (float)(uint)Flags;
        target[3] = Yaw;
        target[4] = Latitude;
        target[5] = Longitude;
        target[6] = Altitude;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static NavTakeoffCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        (NavTakeoffFlags)(uint)source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
