// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Takeoff from local position (local frame only)
/// <para>MAV_CMD entry: <c>MAV_CMD_NAV_TAKEOFF_LOCAL</c> (value 24).</para>
/// </summary>
public readonly record struct NavTakeoffLocalCommand(
    float Pitch,
    float Param2,
    float AscendRate,
    float Yaw,
    float YPosition,
    float XPosition,
    float ZPosition)
{
    public const uint CommandId = 24u;
    public const string CommandName = "MAV_CMD_NAV_TAKEOFF_LOCAL";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Pitch;
        target[1] = Param2;
        target[2] = AscendRate;
        target[3] = Yaw;
        target[4] = YPosition;
        target[5] = XPosition;
        target[6] = ZPosition;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static NavTakeoffLocalCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
