// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Takeoff from ground using VTOL mode, and transition to forward flight with specified heading. The command should be ignored by vehicles that dont support both VTOL and fixed-wing flight (multicopters, boats,etc.).
/// <para>MAV_CMD entry: <c>MAV_CMD_NAV_VTOL_TAKEOFF</c> (value 84).</para>
/// </summary>
public readonly record struct NavVtolTakeoffCommand(
    float Param1,
    VtolTransitionHeading TransitionHeading,
    float Param3,
    float YawAngle,
    float Latitude,
    float Longitude,
    float Altitude)
{
    public const uint CommandId = 84u;
    public const string CommandName = "MAV_CMD_NAV_VTOL_TAKEOFF";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Param1;
        target[1] = (float)(uint)TransitionHeading;
        target[2] = Param3;
        target[3] = YawAngle;
        target[4] = Latitude;
        target[5] = Longitude;
        target[6] = Altitude;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static NavVtolTakeoffCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        (VtolTransitionHeading)(uint)source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
