// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Land using VTOL mode
/// <para>MAV_CMD entry: <c>MAV_CMD_NAV_VTOL_LAND</c> (value 85).</para>
/// </summary>
public readonly record struct NavVtolLandCommand(
    NavVtolLandOptions LandOptions,
    float Param2,
    float ApproachAltitude,
    float Yaw,
    float Latitude,
    float Longitude,
    float GroundAltitude)
{
    public const uint CommandId = 85u;
    public const string CommandName = "MAV_CMD_NAV_VTOL_LAND";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = (float)(uint)LandOptions;
        target[1] = Param2;
        target[2] = ApproachAltitude;
        target[3] = Yaw;
        target[4] = Latitude;
        target[5] = Longitude;
        target[6] = GroundAltitude;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static NavVtolLandCommand Unpack(System.ReadOnlySpan<float> source) => new(
        (NavVtolLandOptions)(uint)source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
