// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Mission command to set a Camera Auto Mount Pivoting Oblique Survey (Replaces CAM_TRIGG_DIST for this purpose). The camera is triggered each time this distance is exceeded, then the mount moves to the next position. Params 4~6 set-up the angle limits and number of positions for oblique survey, where mount-enabled vehicles automatically roll the camera between shots to emulate an oblique camera setup (providing an increased HFOV). This command can also be used to set the shutter integration time for the camera.
/// <para>MAV_CMD entry: <c>MAV_CMD_OBLIQUE_SURVEY</c> (value 260).</para>
/// </summary>
public readonly record struct ObliqueSurveyCommand(
    float Distance,
    float Shutter,
    float MinInterval,
    float Positions,
    float RollAngle,
    float PitchAngle,
    float Param7)
{
    public const uint CommandId = 260u;
    public const string CommandName = "MAV_CMD_OBLIQUE_SURVEY";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Distance;
        target[1] = Shutter;
        target[2] = MinInterval;
        target[3] = Positions;
        target[4] = RollAngle;
        target[5] = PitchAngle;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static ObliqueSurveyCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
