// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Override current mission with command to pause mission, pause mission and move to position, continue/resume mission. When param 1 indicates that the mission is paused (MAV_GOTO_DO_HOLD), param 2 defines whether it holds in place or moves to another position.
/// <para>MAV_CMD entry: <c>MAV_CMD_OVERRIDE_GOTO</c> (value 252).</para>
/// </summary>
public readonly record struct OverrideGotoCommand(
    MavGoto Continue,
    MavGoto Position,
    MavFrame Frame,
    float Yaw,
    float LatitudeX,
    float LongitudeY,
    float AltitudeZ)
{
    public const uint CommandId = 252u;
    public const string CommandName = "MAV_CMD_OVERRIDE_GOTO";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = (float)(uint)Continue;
        target[1] = (float)(uint)Position;
        target[2] = (float)(uint)Frame;
        target[3] = Yaw;
        target[4] = LatitudeX;
        target[5] = LongitudeY;
        target[6] = AltitudeZ;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static OverrideGotoCommand Unpack(System.ReadOnlySpan<float> source) => new(
        (MavGoto)(uint)source[0],
        (MavGoto)(uint)source[1],
        (MavFrame)(uint)source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
