// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Create a panorama at the current position
/// <para>MAV_CMD entry: <c>MAV_CMD_PANORAMA_CREATE</c> (value 2800).</para>
/// </summary>
public readonly record struct PanoramaCreateCommand(
    float HorizontalAngle,
    float VerticalAngle,
    float HorizontalSpeed,
    float VerticalSpeed,
    float Param5,
    float Param6,
    float Param7)
{
    public const uint CommandId = 2800u;
    public const string CommandName = "MAV_CMD_PANORAMA_CREATE";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = HorizontalAngle;
        target[1] = VerticalAngle;
        target[2] = HorizontalSpeed;
        target[3] = VerticalSpeed;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static PanoramaCreateCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
