// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Deploy payload on a Lat / Lon / Alt position. This includes the navigation to reach the required release position and velocity.
/// <para>MAV_CMD entry: <c>MAV_CMD_PAYLOAD_PREPARE_DEPLOY</c> (value 30001).</para>
/// </summary>
public readonly record struct PayloadPrepareDeployCommand(
    float OperationMode,
    float ApproachVector,
    float GroundSpeed,
    float AltitudeClearance,
    float Latitude,
    float Longitude,
    float Altitude)
{
    public const uint CommandId = 30001u;
    public const string CommandName = "MAV_CMD_PAYLOAD_PREPARE_DEPLOY";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = OperationMode;
        target[1] = ApproachVector;
        target[2] = GroundSpeed;
        target[3] = AltitudeClearance;
        target[4] = Latitude;
        target[5] = Longitude;
        target[6] = Altitude;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static PayloadPrepareDeployCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
