// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Trigger calibration. This command will be only accepted if in pre-flight mode. Except for Temperature Calibration, only one sensor should be set in a single message and all others should be zero.
/// <para>MAV_CMD entry: <c>MAV_CMD_PREFLIGHT_CALIBRATION</c> (value 241).</para>
/// </summary>
public readonly record struct PreflightCalibrationCommand(
    float GyroTemperature,
    PreflightCalibrationMagnetometer Magnetometer,
    MavBool GroundPressure,
    float RemoteControl,
    PreflightCalibrationAccelerometer Accelerometer,
    float CompmotOrAirspeed,
    float ESCOrBaro)
{
    public const uint CommandId = 241u;
    public const string CommandName = "MAV_CMD_PREFLIGHT_CALIBRATION";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = GyroTemperature;
        target[1] = (float)(uint)Magnetometer;
        target[2] = (float)(uint)GroundPressure;
        target[3] = RemoteControl;
        target[4] = (float)(uint)Accelerometer;
        target[5] = CompmotOrAirspeed;
        target[6] = ESCOrBaro;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static PreflightCalibrationCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        (PreflightCalibrationMagnetometer)(uint)source[1],
        (MavBool)(uint)source[2],
        source[3],
        (PreflightCalibrationAccelerometer)(uint)source[4],
        source[5],
        source[6]);
}
