// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Request the reboot or shutdown of system components.
/// <para>MAV_CMD entry: <c>MAV_CMD_PREFLIGHT_REBOOT_SHUTDOWN</c> (value 246).</para>
/// </summary>
public readonly record struct PreflightRebootShutdownCommand(
    RebootShutdownAction Autopilot,
    RebootShutdownAction Companion,
    RebootShutdownAction ComponentAction,
    float ComponentID,
    float Param5,
    RebootShutdownConditions Conditions,
    float Param7)
{
    public const uint CommandId = 246u;
    public const string CommandName = "MAV_CMD_PREFLIGHT_REBOOT_SHUTDOWN";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = (float)(uint)Autopilot;
        target[1] = (float)(uint)Companion;
        target[2] = (float)(uint)ComponentAction;
        target[3] = ComponentID;
        target[4] = Param5;
        target[5] = (float)(uint)Conditions;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static PreflightRebootShutdownCommand Unpack(System.ReadOnlySpan<float> source) => new(
        (RebootShutdownAction)(uint)source[0],
        (RebootShutdownAction)(uint)source[1],
        (RebootShutdownAction)(uint)source[2],
        source[3],
        source[4],
        (RebootShutdownConditions)(uint)source[5],
        source[6]);
}
