// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Request storage of different parameter values and logs. This command will be only accepted if in pre-flight mode.
/// <para>MAV_CMD entry: <c>MAV_CMD_PREFLIGHT_STORAGE</c> (value 245).</para>
/// </summary>
public readonly record struct PreflightStorageCommand(
    PreflightStorageParameterAction ParameterStorage,
    PreflightStorageMissionAction MissionStorage,
    float LoggingRate,
    float Param4,
    float Param5,
    float Param6,
    float Param7)
{
    public const uint CommandId = 245u;
    public const string CommandName = "MAV_CMD_PREFLIGHT_STORAGE";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = (float)(uint)ParameterStorage;
        target[1] = (float)(uint)MissionStorage;
        target[2] = LoggingRate;
        target[3] = Param4;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static PreflightStorageCommand Unpack(System.ReadOnlySpan<float> source) => new(
        (PreflightStorageParameterAction)(uint)source[0],
        (PreflightStorageMissionAction)(uint)source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
