// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Set sensor offsets. This command will be only accepted if in pre-flight mode.
/// <para>MAV_CMD entry: <c>MAV_CMD_PREFLIGHT_SET_SENSOR_OFFSETS</c> (value 242).</para>
/// </summary>
public readonly record struct PreflightSetSensorOffsetsCommand(
    float SensorType,
    float XOffset,
    float YOffset,
    float ZOffset,
    float Param5,
    float Param6,
    float Param7)
{
    public const uint CommandId = 242u;
    public const string CommandName = "MAV_CMD_PREFLIGHT_SET_SENSOR_OFFSETS";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = SensorType;
        target[1] = XOffset;
        target[2] = YOffset;
        target[3] = ZOffset;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static PreflightSetSensorOffsetsCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
