// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Request the target system(s) emit a single instance of a specified message (i.e. a "one-shot" version of MAV_CMD_SET_MESSAGE_INTERVAL).
/// <para>MAV_CMD entry: <c>MAV_CMD_REQUEST_MESSAGE</c> (value 512).</para>
/// </summary>
public readonly record struct RequestMessageCommand(
    float MessageID,
    float ReqParam1,
    float ReqParam2,
    float ReqParam3,
    float ReqParam4,
    float ReqParam5,
    float ResponseTarget)
{
    public const uint CommandId = 512u;
    public const string CommandName = "MAV_CMD_REQUEST_MESSAGE";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = MessageID;
        target[1] = ReqParam1;
        target[2] = ReqParam2;
        target[3] = ReqParam3;
        target[4] = ReqParam4;
        target[5] = ReqParam5;
        target[6] = ResponseTarget;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static RequestMessageCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
