// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Instructs a target system to run pre-arm checks.
/// This allows preflight checks to be run on demand, which may be useful on systems that normally run them at low rate, or which do not trigger checks when the armable state might have changed.
/// This command should return MAV_RESULT_ACCEPTED if it will run the checks.
/// The results of the checks are usually then reported in SYS_STATUS messages (this is system-specific).
/// The command should return MAV_RESULT_TEMPORARILY_REJECTED if the system is already armed.
/// <para>MAV_CMD entry: <c>MAV_CMD_RUN_PREARM_CHECKS</c> (value 401).</para>
/// </summary>
public readonly record struct RunPrearmChecksCommand(
    float Param1,
    float Param2,
    float Param3,
    float Param4,
    float Param5,
    float Param6,
    float Param7)
{
    public const uint CommandId = 401u;
    public const string CommandName = "MAV_CMD_RUN_PREARM_CHECKS";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Param1;
        target[1] = Param2;
        target[2] = Param3;
        target[3] = Param4;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static RunPrearmChecksCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
