// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Set camera source. Changes the camera's active sources on cameras with multiple image sensors.
/// <para>MAV_CMD entry: <c>MAV_CMD_SET_CAMERA_SOURCE</c> (value 534).</para>
/// </summary>
public readonly record struct SetCameraSourceCommand(
    float DeviceId,
    CameraSource PrimarySource,
    CameraSource SecondarySource,
    float Param4,
    float Param5,
    float Param6,
    float Param7)
{
    public const uint CommandId = 534u;
    public const string CommandName = "MAV_CMD_SET_CAMERA_SOURCE";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = DeviceId;
        target[1] = (float)(uint)PrimarySource;
        target[2] = (float)(uint)SecondarySource;
        target[3] = Param4;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static SetCameraSourceCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        (CameraSource)(uint)source[1],
        (CameraSource)(uint)source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
