// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Set camera zoom. Camera must respond with a CAMERA_SETTINGS message (on success).
/// <para>MAV_CMD entry: <c>MAV_CMD_SET_CAMERA_ZOOM</c> (value 531).</para>
/// </summary>
public readonly record struct SetCameraZoomCommand(
    CameraZoomType ZoomType,
    float ZoomValue,
    float TargetCameraID,
    float Param4,
    float Param5,
    float Param6,
    float Param7)
{
    public const uint CommandId = 531u;
    public const string CommandName = "MAV_CMD_SET_CAMERA_ZOOM";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = (float)(uint)ZoomType;
        target[1] = ZoomValue;
        target[2] = TargetCameraID;
        target[3] = Param4;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static SetCameraZoomCommand Unpack(System.ReadOnlySpan<float> source) => new(
        (CameraZoomType)(uint)source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
