// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Set camera running mode. Use NaN for reserved values. GCS will send a MAV_CMD_REQUEST_VIDEO_STREAM_STATUS command after a mode change if the camera supports video streaming.
/// <para>MAV_CMD entry: <c>MAV_CMD_SET_CAMERA_MODE</c> (value 530).</para>
/// </summary>
public readonly record struct SetCameraModeCommand(
    float Id,
    CameraMode CameraMode,
    float Param3,
    float Param4,
    float Param5,
    float Param6,
    float Param7)
{
    public const uint CommandId = 530u;
    public const string CommandName = "MAV_CMD_SET_CAMERA_MODE";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Id;
        target[1] = (float)(uint)CameraMode;
        target[2] = Param3;
        target[3] = Param4;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static SetCameraModeCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        (CameraMode)(uint)source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
