// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// This command sets submode circle when vehicle is in guided mode. Vehicle flies along a circle facing the center of the circle. The user can input the velocity along the circle and change the radius. If no input is given the vehicle will hold position.
/// <para>MAV_CMD entry: <c>MAV_CMD_SET_GUIDED_SUBMODE_CIRCLE</c> (value 4001).</para>
/// </summary>
public readonly record struct SetGuidedSubmodeCircleCommand(
    float Radius,
    float Param2,
    float Param3,
    float Param4,
    float Latitude,
    float Longitude,
    float Param7)
{
    public const uint CommandId = 4001u;
    public const string CommandName = "MAV_CMD_SET_GUIDED_SUBMODE_CIRCLE";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = Radius;
        target[1] = Param2;
        target[2] = Param3;
        target[3] = Param4;
        target[4] = Latitude;
        target[5] = Longitude;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static SetGuidedSubmodeCircleCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
