// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Set the interval between messages for a particular MAVLink message ID. This interface replaces REQUEST_DATA_STREAM.
/// <para>MAV_CMD entry: <c>MAV_CMD_SET_MESSAGE_INTERVAL</c> (value 511).</para>
/// </summary>
public readonly record struct SetMessageIntervalCommand(
    float MessageID,
    float Interval,
    float ReqParam3,
    float ReqParam4,
    float ReqParam5,
    float ReqParam6,
    float ResponseTarget)
{
    public const uint CommandId = 511u;
    public const string CommandName = "MAV_CMD_SET_MESSAGE_INTERVAL";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = MessageID;
        target[1] = Interval;
        target[2] = ReqParam3;
        target[3] = ReqParam4;
        target[4] = ReqParam5;
        target[5] = ReqParam6;
        target[6] = ResponseTarget;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static SetMessageIntervalCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
