// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Set that a particular storage is the preferred location for saving photos, videos, and/or other media (e.g. to set that an SD card is used for storing videos).
/// There can only be one preferred save location for each particular media type: setting a media usage flag will clear/reset that same flag if set on any other storage.
/// If no flag is set the system should use its default storage.
/// A target system can choose to always use default storage, in which case it should ACK the command with MAV_RESULT_UNSUPPORTED.
/// A target system can choose to not allow a particular storage to be set as preferred storage, in which case it should ACK the command with MAV_RESULT_DENIED.
/// <para>MAV_CMD entry: <c>MAV_CMD_SET_STORAGE_USAGE</c> (value 533).</para>
/// </summary>
public readonly record struct SetStorageUsageCommand(
    float StorageID,
    StorageUsageFlag Usage,
    float Param3,
    float Param4,
    float Param5,
    float Param6,
    float Param7)
{
    public const uint CommandId = 533u;
    public const string CommandName = "MAV_CMD_SET_STORAGE_USAGE";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = StorageID;
        target[1] = (float)(uint)Usage;
        target[2] = Param3;
        target[3] = Param4;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static SetStorageUsageCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        (StorageUsageFlag)(uint)source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
