// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Starts receiver pairing.
/// <para>MAV_CMD entry: <c>MAV_CMD_START_RX_PAIR</c> (value 500).</para>
/// </summary>
public readonly record struct StartRxPairCommand(
    RcType RCType,
    RcSubType RCSubType,
    float Param3,
    float Param4,
    float Param5,
    float Param6,
    float Param7)
{
    public const uint CommandId = 500u;
    public const string CommandName = "MAV_CMD_START_RX_PAIR";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = (float)(uint)RCType;
        target[1] = (float)(uint)RCSubType;
        target[2] = Param3;
        target[3] = Param4;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static StartRxPairCommand Unpack(System.ReadOnlySpan<float> source) => new(
        (RcType)(uint)source[0],
        (RcSubType)(uint)source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
