// <auto-generated by MavNet.CodeGen />
using MavNet.Protocol.Generated.Enums;

namespace MavNet.Protocol.Generated.Commands;

/// <summary>
/// Starts video capture (recording).
/// <para>MAV_CMD entry: <c>MAV_CMD_VIDEO_START_CAPTURE</c> (value 2500).</para>
/// </summary>
public readonly record struct VideoStartCaptureCommand(
    float StreamID,
    float StatusFrequency,
    float TargetCameraID,
    float Param4,
    float Param5,
    float Param6,
    float Param7)
{
    public const uint CommandId = 2500u;
    public const string CommandName = "MAV_CMD_VIDEO_START_CAPTURE";

    /// <summary>Pack into the seven-float COMMAND_LONG param block. <paramref name="target"/> must be at least 7 elements.</summary>
    public void PackParams(System.Span<float> target)
    {
        target[0] = StreamID;
        target[1] = StatusFrequency;
        target[2] = TargetCameraID;
        target[3] = Param4;
        target[4] = Param5;
        target[5] = Param6;
        target[6] = Param7;
    }

    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>
    public static VideoStartCaptureCommand Unpack(System.ReadOnlySpan<float> source) => new(
        source[0],
        source[1],
        source[2],
        source[3],
        source[4],
        source[5],
        source[6]);
}
