using System.Text;

namespace MavNet.CodeGen.Emitters;

/// <summary>
/// Emits one C# source file per MAV_CMD entry into <c>Commands/</c>. Each file
/// contains a <c>readonly record struct</c> with named, strongly-typed param
/// properties (mapped from the XML &lt;param index="N"&gt; tags) plus Pack/Unpack
/// helpers that round-trip through the seven-float COMMAND_LONG param slots.
///
/// <para>Commands are decoupled from any specific message type — they describe
/// the semantic shape of a MAV_CMD, not its wire transport. A builder can compose
/// them into a COMMAND_LONG, COMMAND_INT, or a mission item without the command
/// definition knowing which.</para>
/// </summary>
internal static class CommandEmitter
{
    public static void EmitAll(Spec spec, string outputDir)
    {
        var commandsDir = Path.Combine(outputDir, "Commands");
        Directory.CreateDirectory(commandsDir);

        var mavCmd = spec.Enums.FirstOrDefault(e => e.Name == "MAV_CMD");
        if (mavCmd is null) return;

        var emittedTypeNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (var entry in mavCmd.Entries)
        {
            var typeName = Casing.EntryName(entry.Name, mavCmd.Name) + "Command";
            // Dialect dedup — same as EnumEmitter; first wins.
            if (!emittedTypeNames.Add(typeName)) continue;
            var path = Path.Combine(commandsDir, typeName + ".cs");
            File.WriteAllText(path, Render(entry, typeName));
        }
    }

    private static string Render(EnumEntrySpec entry, string typeName)
    {
        // Normalize to 7 params (some entries declare fewer); missing slots become "ParamN".
        var slots = new (string Label, string CsType, string? EnumName)[7];
        for (var i = 0; i < 7; i++)
            slots[i] = ($"Param{i + 1}", "float", null);
        foreach (var p in entry.Params)
        {
            if (p.Index < 1 || p.Index > 7) continue;
            var label = SanitizeLabel(p.Label, p.Index);
            var cs = p.EnumName is not null ? Casing.PascalCase(p.EnumName) : "float";
            slots[p.Index - 1] = (label, cs, p.EnumName);
        }
        // Deduplicate property names (e.g. two params labelled "Empty").
        DedupePropertyNames(slots);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by MavNet.CodeGen />");
        sb.AppendLine("using MavNet.Protocol.Generated.Enums;");
        sb.AppendLine();
        sb.AppendLine("namespace MavNet.Protocol.Generated.Commands;");
        sb.AppendLine();
        if (entry.Description.Length > 0)
        {
            sb.AppendLine("/// <summary>");
            foreach (var line in entry.Description.Split('\n'))
                sb.AppendLine("/// " + line.Trim().Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;"));
            sb.AppendLine($"/// <para>MAV_CMD entry: <c>{entry.Name}</c> (value {entry.Value}).</para>");
            sb.AppendLine("/// </summary>");
        }
        else
        {
            sb.AppendLine($"/// <summary>MAV_CMD entry: <c>{entry.Name}</c> (value {entry.Value}).</summary>");
        }
        sb.AppendLine($"public readonly record struct {typeName}(");
        for (var i = 0; i < 7; i++)
        {
            var sep = i == 6 ? ")" : ",";
            sb.AppendLine($"    {slots[i].CsType} {slots[i].Label}{sep}");
        }
        sb.AppendLine("{");
        sb.AppendLine($"    public const uint CommandId = {entry.Value}u;");
        sb.AppendLine($"    public const string CommandName = \"{entry.Name}\";");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Pack into the seven-float COMMAND_LONG param block. " +
                      "<paramref name=\"target\"/> must be at least 7 elements.</summary>");
        sb.AppendLine("    public void PackParams(System.Span<float> target)");
        sb.AppendLine("    {");
        for (var i = 0; i < 7; i++)
            sb.AppendLine($"        target[{i}] = {ToFloat(slots[i])};");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Unpack from the seven-float COMMAND_LONG param block.</summary>");
        sb.AppendLine($"    public static {typeName} Unpack(System.ReadOnlySpan<float> source) => new(");
        for (var i = 0; i < 7; i++)
        {
            var sep = i == 6 ? ");" : ",";
            sb.AppendLine($"        {FromFloat(slots[i], $"source[{i}]")}{sep}");
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string ToFloat((string Label, string CsType, string? EnumName) slot) =>
        slot.EnumName is null ? slot.Label : $"(float)(uint){slot.Label}";

    private static string FromFloat((string Label, string CsType, string? EnumName) slot, string source) =>
        slot.EnumName is null ? source : $"({slot.CsType})(uint){source}";

    private static string SanitizeLabel(string label, int index)
    {
        // Label is human text like "Pitch", "Descend Rate", "X Position". Strip non-identifier
        // chars and PascalCase. Falls back to ParamN if the result is empty/unusable.
        var cleaned = new StringBuilder();
        var capitalizeNext = true;
        foreach (var ch in label)
        {
            if (char.IsLetterOrDigit(ch))
            {
                cleaned.Append(capitalizeNext ? char.ToUpperInvariant(ch) : ch);
                capitalizeNext = false;
            }
            else
            {
                capitalizeNext = true;
            }
        }
        var result = cleaned.ToString();
        if (result.Length == 0 || char.IsDigit(result[0])) result = $"Param{index}";
        // "Empty" / "Reserved" labels are MAVLink convention for unused slots — keep them as Param N
        // so a builder can ignore them rather than typing "Empty" everywhere.
        if (result.Equals("Empty", System.StringComparison.OrdinalIgnoreCase) ||
            result.Equals("Reserved", System.StringComparison.OrdinalIgnoreCase))
            result = $"Param{index}";
        return result;
    }

    private static void DedupePropertyNames((string Label, string CsType, string? EnumName)[] slots)
    {
        var seen = new Dictionary<string, int>(StringComparer.Ordinal);
        for (var i = 0; i < slots.Length; i++)
        {
            var name = slots[i].Label;
            if (seen.TryGetValue(name, out var count))
            {
                seen[name] = count + 1;
                slots[i] = (name + (count + 1), slots[i].CsType, slots[i].EnumName);
            }
            else seen[name] = 1;
        }
    }
}
