using System.Text;

namespace MavNet.CodeGen.Emitters;

internal static class EnumEmitter
{
    public static void EmitAll(Spec spec, string outputDir)
    {
        Directory.CreateDirectory(outputDir);
        foreach (var e in spec.Enums)
        {
            var path = Path.Combine(outputDir, Casing.PascalCase(e.Name) + ".cs");
            File.WriteAllText(path, Render(e));
        }
    }

    private static string Render(EnumSpec e)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by MavNet.CodeGen />");
        sb.AppendLine("namespace MavNet.Protocol.Generated.Enums;");
        sb.AppendLine();
        // Pick smallest underlying type that fits every entry. Default `int` overflows
        // when bitmask flags use the high bit of a uint32 field (e.g. 0x80000000).
        var max = e.Entries.Count == 0 ? 0 : e.Entries.Max(en => en.Value);
        var min = e.Entries.Count == 0 ? 0 : e.Entries.Min(en => en.Value);
        var underlying = (min >= 0 && max > int.MaxValue) ? " : uint"
                       : (min < int.MinValue || max > uint.MaxValue) ? " : long"
                       : "";
        if (e.IsBitmask) sb.AppendLine("[System.Flags]");
        sb.AppendLine($"public enum {Casing.PascalCase(e.Name)}{underlying}");
        sb.AppendLine("{");
        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (var entry in e.Entries)
        {
            var name = Casing.EntryName(entry.Name, e.Name);
            // Some MAVLink dialects have duplicate values or near-duplicate stripped names — keep first.
            if (!seen.Add(name)) continue;
            var suffix = underlying.Contains("uint") ? "U" : underlying.Contains("long") ? "L" : "";
            sb.AppendLine($"    {name} = {entry.Value}{suffix},");
        }
        sb.AppendLine("}");
        return sb.ToString();
    }
}
