using MavNet.CodeGen;
using System.Text;

namespace MavNet.CodeGen.Emitters;

/// <summary>
/// Emits one C# source file per allowlisted message into <c>Messages/</c>. Each
/// contains a <c>readonly record struct</c> with PascalCase properties, plus
/// MsgId / CrcExtra / Min+MaxPayloadLength constants and Decode/Encode methods.
/// Implements <see cref="MavNet.Protocol.IMavlinkMessage{TSelf}"/>.
/// </summary>
internal static class MessageEmitter
{
    public static void EmitAll(Spec spec, IReadOnlySet<string> allowlist, string outputDir)
    {
        var messagesDir = Path.Combine(outputDir, "Messages");
        Directory.CreateDirectory(messagesDir);
        foreach (var msg in spec.Messages)
        {
            if (!allowlist.Contains(msg.Name)) continue;
            var path = Path.Combine(messagesDir, Casing.PascalCase(msg.Name) + ".cs");
            File.WriteAllText(path, Render(msg));
        }
    }

    private static string Render(MessageSpec msg)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by MavNet.CodeGen />");
        sb.AppendLine("using System.Buffers.Binary;");
        sb.AppendLine("using MavNet.Protocol;");
        sb.AppendLine("using MavNet.Protocol.Generated.Enums;");
        sb.AppendLine();
        sb.AppendLine("namespace MavNet.Protocol.Generated.Messages;");
        sb.AppendLine();
        var typeName = Casing.PascalCase(msg.Name);

        // Build (offset, CSharpType, propName, fieldSpec) tuples.
        var offset = 0;
        var fieldInfos = new List<(int Offset, string CsType, string Prop, FieldSpec F)>();
        foreach (var f in msg.Fields)
        {
            var csType = f.EnumName is not null ? Casing.PascalCase(f.EnumName) : f.Type.CSharpFieldType;
            var prop = Casing.PascalCase(f.Name);
            fieldInfos.Add((offset, csType, prop, f));
            offset += f.Type.WireSize;
        }

        sb.AppendLine($"public readonly record struct {typeName}(");
        for (var i = 0; i < fieldInfos.Count; i++)
        {
            var (_, csType, prop, _) = fieldInfos[i];
            var sep = i == fieldInfos.Count - 1 ? $") : IMavlinkMessage<{typeName}>" : ",";
            sb.AppendLine($"    {csType} {prop}{sep}");
        }
        sb.AppendLine("{");
        sb.AppendLine($"    public const uint MsgId = {msg.Id}u;");
        sb.AppendLine($"    public const byte CrcExtra = {CrcExtraComputer.Compute(msg)};");
        sb.AppendLine($"    public const byte MinPayloadLength = {msg.MinPayloadLength};");
        sb.AppendLine($"    public const byte MaxPayloadLength = {msg.MaxPayloadLength};");
        sb.AppendLine();
        sb.AppendLine($"    static uint IMavlinkMessage<{typeName}>.MsgId             => MsgId;");
        sb.AppendLine($"    static byte IMavlinkMessage<{typeName}>.CrcExtra          => CrcExtra;");
        sb.AppendLine($"    static byte IMavlinkMessage<{typeName}>.MinPayloadLength  => MinPayloadLength;");
        sb.AppendLine($"    static byte IMavlinkMessage<{typeName}>.MaxPayloadLength  => MaxPayloadLength;");
        sb.AppendLine();

        // Decode
        sb.AppendLine($"    public static {typeName} Decode(System.ReadOnlySpan<byte> payload)");
        sb.AppendLine("    {");
        sb.AppendLine("        // MAVLink v2 senders may strip trailing zero bytes — pad up to max length.");
        sb.AppendLine("        System.Span<byte> p = stackalloc byte[MaxPayloadLength];");
        sb.AppendLine("        payload[..System.Math.Min(payload.Length, (int)MaxPayloadLength)].CopyTo(p);");
        sb.AppendLine($"        return new {typeName}(");
        for (var i = 0; i < fieldInfos.Count; i++)
        {
            var fi = fieldInfos[i];
            var sep = i == fieldInfos.Count - 1 ? ");" : ",";
            sb.AppendLine($"            {ReadExpr(fi.F, fi.Offset, fi.CsType)}{sep}");
        }
        sb.AppendLine("    }");
        sb.AppendLine();

        // Encode (writes full untruncated payload — caller decides whether to truncate).
        sb.AppendLine("    /// <summary>Encode the full untruncated payload. Caller may strip trailing zero bytes");
        sb.AppendLine("    /// down to <see cref=\"MinPayloadLength\"/> for on-wire MAVLink v2 truncation.</summary>");
        sb.AppendLine("    public void Encode(System.Span<byte> payload)");
        sb.AppendLine("    {");
        foreach (var fi in fieldInfos)
        {
            sb.AppendLine($"        {WriteStmt(fi.F, fi.Offset, fi.Prop)};");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string ReadExpr(FieldSpec f, int offset, string csType)
    {
        var sliceRange = $"{offset}..{offset + f.Type.WireSize}";
        var primitiveRead = f.Type.Wire switch
        {
            "uint8_t" or "uint8_t_mavlink_version" or "char" => $"p[{offset}]",
            "int8_t"   => $"(sbyte)p[{offset}]",
            "uint16_t" => $"BinaryPrimitives.ReadUInt16LittleEndian(p[{sliceRange}])",
            "int16_t"  => $"BinaryPrimitives.ReadInt16LittleEndian(p[{sliceRange}])",
            "uint32_t" => $"BinaryPrimitives.ReadUInt32LittleEndian(p[{sliceRange}])",
            "int32_t"  => $"BinaryPrimitives.ReadInt32LittleEndian(p[{sliceRange}])",
            "uint64_t" => $"BinaryPrimitives.ReadUInt64LittleEndian(p[{sliceRange}])",
            "int64_t"  => $"BinaryPrimitives.ReadInt64LittleEndian(p[{sliceRange}])",
            "float"    => $"BinaryPrimitives.ReadSingleLittleEndian(p[{sliceRange}])",
            "double"   => $"BinaryPrimitives.ReadDoubleLittleEndian(p[{sliceRange}])",
            _ => throw new NotSupportedException($"Phase-2 emitter doesn't handle MAVLink type '{f.Type.Wire}' yet (field {f.Name})")
        };
        if (f.Type.IsArray)
            throw new NotSupportedException($"Phase-2 emitter doesn't handle array fields yet ({f.Name})");
        return f.EnumName is null ? primitiveRead : $"({csType}){primitiveRead}";
    }

    private static string WriteStmt(FieldSpec f, int offset, string prop)
    {
        var sliceRange = $"{offset}..{offset + f.Type.WireSize}";
        if (f.Type.IsArray)
            throw new NotSupportedException($"Phase-2 emitter doesn't handle array fields yet ({f.Name})");
        var valueExpr = f.EnumName is null ? prop : ToPrimitive(prop, f.Type.Wire);
        return f.Type.Wire switch
        {
            "uint8_t" or "uint8_t_mavlink_version" or "char" => $"payload[{offset}] = {valueExpr}",
            "int8_t"   => $"payload[{offset}] = (byte){valueExpr}",
            "uint16_t" => $"BinaryPrimitives.WriteUInt16LittleEndian(payload[{sliceRange}], {valueExpr})",
            "int16_t"  => $"BinaryPrimitives.WriteInt16LittleEndian(payload[{sliceRange}], {valueExpr})",
            "uint32_t" => $"BinaryPrimitives.WriteUInt32LittleEndian(payload[{sliceRange}], {valueExpr})",
            "int32_t"  => $"BinaryPrimitives.WriteInt32LittleEndian(payload[{sliceRange}], {valueExpr})",
            "uint64_t" => $"BinaryPrimitives.WriteUInt64LittleEndian(payload[{sliceRange}], {valueExpr})",
            "int64_t"  => $"BinaryPrimitives.WriteInt64LittleEndian(payload[{sliceRange}], {valueExpr})",
            "float"    => $"BinaryPrimitives.WriteSingleLittleEndian(payload[{sliceRange}], {valueExpr})",
            "double"   => $"BinaryPrimitives.WriteDoubleLittleEndian(payload[{sliceRange}], {valueExpr})",
            _ => throw new NotSupportedException($"Phase-2 emitter doesn't handle MAVLink type '{f.Type.Wire}' yet (field {f.Name})")
        };
    }

    private static string ToPrimitive(string prop, string wire) => wire switch
    {
        "uint8_t" or "uint8_t_mavlink_version" or "char" => $"(byte){prop}",
        "int8_t"   => $"(sbyte){prop}",
        "uint16_t" => $"(ushort){prop}",
        "int16_t"  => $"(short){prop}",
        "uint32_t" => $"(uint){prop}",
        "int32_t"  => $"(int){prop}",
        "uint64_t" => $"(ulong){prop}",
        "int64_t"  => $"(long){prop}",
        _ => prop
    };
}
