using System.Text;

namespace MavNet.CodeGen.Emitters;

/// <summary>
/// Emits MessageRegistry.cs — a frozen lookup of MAVLink message metadata covering
/// every message in the spec (not just allowlisted/decoded ones). The frame parser
/// uses CrcExtra to validate inbound CRCs regardless of whether the SDK can decode
/// the payload — dropping unknown-but-valid frames would silently break the protocol.
///
/// Output is a FrozenDictionary&lt;uint, MessageInfo&gt; built once at module load.
/// </summary>
internal static class RegistryEmitter
{
    public static void Emit(Spec spec, string outputDir)
    {
        Directory.CreateDirectory(outputDir);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by MavNet.CodeGen />");
        sb.AppendLine("using System.Collections.Frozen;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using MavNet.Protocol;");
        sb.AppendLine();
        sb.AppendLine("namespace MavNet.Protocol.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Lookup of MAVLink message metadata by msgid. Covers every message in the");
        sb.AppendLine("/// generated spec — including messages this SDK doesn't decode — because the");
        sb.AppendLine("/// frame parser needs <c>CrcExtra</c> to validate inbound CRCs regardless of");
        sb.AppendLine("/// decode capability. Decoder presence is tracked separately.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class MessageRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    private static readonly FrozenDictionary<uint, MessageInfo> _byId = BuildEntries().ToFrozenDictionary(static e => e.MsgId);");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Look up message metadata by 24-bit MAVLink msgid. Returns false for unknown ids.</summary>");
        sb.AppendLine("    public static bool TryGet(uint msgId, out MessageInfo info) => _byId.TryGetValue(msgId, out info);");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Every registered message. Stable across calls; safe to enumerate concurrently.</summary>");
        sb.AppendLine("    public static IReadOnlyCollection<MessageInfo> All => _byId.Values;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>True if any message with this id is registered (decodable or not).</summary>");
        sb.AppendLine("    public static bool Contains(uint msgId) => _byId.ContainsKey(msgId);");
        sb.AppendLine();
        sb.AppendLine("    private static IEnumerable<MessageInfo> BuildEntries()");
        sb.AppendLine("    {");
        foreach (var m in spec.Messages)
        {
            var crc = CrcExtraComputer.Compute(m);
            var flags = m.HasExtensions ? "MessageFlags.HasExtensions" : "MessageFlags.None";
            sb.AppendLine(
                $"        yield return new MessageInfo({m.Id}u, {crc}, {m.MinPayloadLength}, {m.MaxPayloadLength}, \"{m.Name}\", {flags});");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        File.WriteAllText(Path.Combine(outputDir, "MessageRegistry.cs"), sb.ToString());
    }
}
